// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type IngestedEvent struct {
	// CloudEvents Specification JSON Schema
	Event           Event   `json:"event"`
	ValidationError *string `json:"validationError,omitempty"`
}

func (o *IngestedEvent) GetEvent() Event {
	if o == nil {
		return Event{}
	}
	return o.Event
}

func (o *IngestedEvent) GetValidationError() *string {
	if o == nil {
		return nil
	}
	return o.ValidationError
}
