package meteredentitlement

import meteredentitlement "github.com/openmeterio/openmeter/internal/entitlement/metered"

type BalanceHistoryParams = meteredentitlement.BalanceHistoryParams
type CreateEntitlementGrantInputs = meteredentitlement.CreateEntitlementGrantInputs
type EntitlementBalance = meteredentitlement.EntitlementBalance
type Connector = meteredentitlement.Connector
type EntitlementBalanceHistoryWindow = meteredentitlement.EntitlementBalanceHistoryWindow
type EntitlementGrant = meteredentitlement.EntitlementGrant
type UsageResetRepo = meteredentitlement.UsageResetRepo
type UsageResetNotFoundError = meteredentitlement.UsageResetNotFoundError
type UsageResetTime = meteredentitlement.UsageResetTime
type WindowSize = meteredentitlement.WindowSize
type MeteredEntitlementValue = meteredentitlement.MeteredEntitlementValue
type ResetEntitlementUsageParams = meteredentitlement.ResetEntitlementUsageParams
