# https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    misspell:
      locale: US
    nolintlint:
      require-specific: true
    revive:
      confidence: 0
    staticcheck:
      checks:
        - "all"
        - "-QF1008"
        # FIXME: re-enable the following checks
        - "-ST1003"
        - "-ST1016"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .dagger/internal
      - .dagger/dagger.gen.go
      - collector/benthos/internal
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/openmeterio/openmeter)
    goimports:
      local-prefixes:
        - github.com/openmeterio/openmeter
  exclusions:
    generated: lax
    paths:
      - .dagger/internal
      - .dagger/dagger.gen.go
      - collector/benthos/internal
      - third_party$
      - builtin$
      - examples$
