extends: [[spectral:oas, recommended]]
rules:
  info-contact: off

  # Disabled due to TypeSpec conversion
  oas3-valid-schema-example: off
  no-$ref-siblings: off
  path-params: off
  oas3-unused-component: off
