FROM nixos/nix

RUN nix-channel --update

COPY nix-config.cfg /etc/nix/nix.conf

COPY flake.nix flake.lock /tmp/build/

WORKDIR /tmp/build

RUN nix develop --impure .#ci && rm -rf /tmp/build/*

CMD ["/nix/var/nix/profiles/default/bin/sh", "-c", "sleep infinity"]

LABEL org.opencontainers.image.source=https://github.com/turip/test
