services:
  kafka:
    image: confluentinc/cp-kafka:8.2.2@sha256:8e01c0305844d6c05bfb8e86479f5f363bb6a53497625395943a9da780de67ce
    environment:
      CLUSTER_ID: ca497efe-9f82-4b84-890b-d9969a9a2e1c
      KAFKA_BROKER_ID: 0
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # Message timestamp validation
      # See:
      # * https://cwiki.apache.org/confluence/display/KAFKA/KIP-937%3A+Improve+Message+Timestamp+Validation
      # * https://kafka.apache.org/41/configuration/broker-configs/#brokerconfigs_log.message.timestamp.before.max.ms
      # * https://kafka.apache.org/41/configuration/broker-configs/#brokerconfigs_log.message.timestamp.after.max.ms
      KAFKA_LOG_MESSAGE_TIMESTAMP_AFTER_MAX_MS: 9223372036854775807
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9997"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "JMX_PORT=9998",
          "kafka-topics",
          "--bootstrap-server",
          "kafka:9092",
          "--list",
        ]
      interval: 5s
      timeout: 3s
      retries: 30

  clickhouse:
    image: clickhouse/clickhouse-server:26.4-distroless@sha256:cac600869f9e0abc00af3aff60855009326b30acf76702f239ff3459c78208db
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: openmeter
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://clickhouse:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:v2.5.3@sha256:d31f4d4ac8ec010eac1f1e46af060032e39b8f31435a5b578efc245cf8b8d1de
    profiles:
      - dev
    depends_on:
      - clickhouse
    restart: always
    environment:
      VITE_CLICKHOUSE_URL: http://localhost:8123
      VITE_CLICKHOUSE_USER: default
      VITE_CLICKHOUSE_PASS: default

  # Deduplication
  # docker compose --profile redis up
  redis:
    image: redis:8.8.0-alpine3.23@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    command:
      [
        "redis-server",
        "--maxmemory",
        "50mb",
        "--maxmemory-policy",
        "noeviction",
        "--maxmemory-samples",
        "10",
      ]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 30

  # Development
  # docker compose --profile dev up
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:v1.5.0@sha256:7cda86a33344160309fdb65146332e4da65db81a945614f2fe32e210803f6fd1
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: "true"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://kafka-ui:8080/"]
      interval: 10s
      timeout: 5s
      retries: 30

  # Credit
  # docker compose --profile postgres up
  postgres:
    image: postgres:14.23-alpine3.24@sha256:f1341c01408dc7278e9d365ed4f860cd3f87dd16b4464ac326fc0f422083a579
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    configs:
      - source: svix_sql
        target: /docker-entrypoint-initdb.d/svix.sql
        mode: 0444
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 30

  svix:
    image: svix/svix-server:v1.96@sha256:cd3a1c68b65c4ed32552eaaedea6cf323122428db73c43438a832b314e8e0ac8
    environment:
      WAIT_FOR: "true" # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      SVIX_DB_DSN: "postgresql://svix:svix@postgres/svix"
      SVIX_CACHE_TYPE: "redis"
      SVIX_JWT_SECRET: "DUMMY_JWT_SECRET"
      SVIX_LOG_LEVEL: "info"
      SVIX_QUEUE_TYPE: "redis"
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: [ "CMD", "svix-server", "healthcheck", "http://localhost:8071" ]
      interval: 10s
      timeout: 5s
      retries: 30

configs:
  svix_sql:
    content: |
      CREATE USER svix WITH PASSWORD 'svix';
      CREATE DATABASE svix;
      GRANT ALL PRIVILEGES ON DATABASE svix TO svix;
      ALTER DATABASE svix OWNER TO svix;
