// Code generated by @openmeter/typespec-go. DO NOT EDIT.

package operations

import "github.com/openmeterio/openmeter/api/spec/packages/aip-client-go/models/components"

type CreateMeterRequest struct {
	Meter components.CreateMeterRequest `request:"mediaType=application/json"`
}

type CreateMeterResponse struct {
	HTTPMeta components.HTTPMetadata
	Body     *components.Meter
}
