// Code generated by @openmeter/typespec-go. DO NOT EDIT.

package operations

import "github.com/openmeterio/openmeter/api/spec/packages/aip-client-go/models/components"

type CreateCostBasisRequest struct {
	Body components.CreateCostBasisRequest `request:"mediaType=application/json"`
}

type CreateCostBasisResponse struct {
	HTTPMeta components.HTTPMetadata
	Body     *components.BillingCostBasis
}
