//go:generate go run github.com/jmattheis/goverter/cmd/goverter gen ./
package customersbilling

import (
	apiOld "github.com/openmeterio/openmeter/api"
	api "github.com/openmeterio/openmeter/api/v3"
)

// goverter:variables
// goverter:skipCopySameType
// goverter:output:file ./convert.gen.go
// goverter:useZeroValueOnPointerInconsistency
// goverter:useUnderlyingTypeMethods
// goverter:matchIgnoreCase
// goverter:enum:unknown @error
var (
	ConvertToCreateStripeCheckoutSessionRequestOptions func(source api.BillingAppStripeCreateCheckoutSessionRequestOptions) (apiOld.CreateStripeCheckoutSessionRequestOptions, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionBillingAddressCollectionAuto CreateStripeCheckoutSessionBillingAddressCollectionAuto
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionBillingAddressCollectionRequired CreateStripeCheckoutSessionBillingAddressCollectionRequired
	ConvertToCreateStripeCheckoutSessionBillingAddressCollection func(source api.BillingAppStripeCreateCheckoutSessionBillingAddressCollection) (apiOld.CreateStripeCheckoutSessionBillingAddressCollection, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPositionAuto CreateStripeCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPositionAuto
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPositionHidden CreateStripeCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPositionHidden
	ConvertToCreateStripeCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPosition func(source api.BillingAppStripeCreateCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPosition) (apiOld.CreateStripeCheckoutSessionConsentCollectionPaymentMethodReuseAgreementPosition, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionConsentCollectionPromotionsAuto CreateStripeCheckoutSessionConsentCollectionPromotionsAuto
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionConsentCollectionPromotionsNone CreateStripeCheckoutSessionConsentCollectionPromotionsNone
	ConvertToCreateStripeCheckoutSessionConsentCollectionPromotions func(source api.BillingAppStripeCreateCheckoutSessionConsentCollectionPromotions) (apiOld.CreateStripeCheckoutSessionConsentCollectionPromotions, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionConsentCollectionTermsOfServiceNone CreateStripeCheckoutSessionConsentCollectionTermsOfServiceNone
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionConsentCollectionTermsOfServiceRequired CreateStripeCheckoutSessionConsentCollectionTermsOfServiceRequired
	ConvertToCreateStripeCheckoutSessionConsentCollectionTermsOfService func(source api.BillingAppStripeCreateCheckoutSessionConsentCollectionTermsOfService) (apiOld.CreateStripeCheckoutSessionConsentCollectionTermsOfService, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionCustomerUpdateBehaviorAuto CreateStripeCheckoutSessionCustomerUpdateBehaviorAuto
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionCustomerUpdateBehaviorNever CreateStripeCheckoutSessionCustomerUpdateBehaviorNever
	ConvertToCreateStripeCheckoutSessionCustomerUpdateBehavior func(source api.BillingAppStripeCreateCheckoutSessionCustomerUpdateBehavior) (apiOld.CreateStripeCheckoutSessionCustomerUpdateBehavior, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionRedirectOnCompletionAlways CreateStripeCheckoutSessionRedirectOnCompletionAlways
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionRedirectOnCompletionIfRequired CreateStripeCheckoutSessionRedirectOnCompletionIfRequired
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionRedirectOnCompletionNever CreateStripeCheckoutSessionRedirectOnCompletionNever
	ConvertToCreateStripeCheckoutSessionRedirectOnCompletion func(source api.BillingAppStripeCreateCheckoutSessionRedirectOnCompletion) (apiOld.CreateStripeCheckoutSessionRedirectOnCompletion, error)

	// goverter:enum:map BillingAppStripeCreateCheckoutSessionTaxIdCollectionRequiredIfSupported CreateCheckoutSessionTaxIdCollectionRequiredIfSupported
	// goverter:enum:map BillingAppStripeCreateCheckoutSessionTaxIdCollectionRequiredNever CreateCheckoutSessionTaxIdCollectionRequiredNever
	ConvertToCreateCheckoutSessionTaxIdCollectionRequired func(source api.BillingAppStripeCreateCheckoutSessionTaxIdCollectionRequired) (apiOld.CreateCheckoutSessionTaxIdCollectionRequired, error)

	// goverter:enum:map BillingAppStripeCheckoutSessionUIModeEmbedded CheckoutSessionUIModeEmbedded
	// goverter:enum:map BillingAppStripeCheckoutSessionUIModeHosted CheckoutSessionUIModeHosted
	ConvertToCheckoutSessionUIMode func(source api.BillingAppStripeCheckoutSessionUIMode) (apiOld.CheckoutSessionUIMode, error)
)
