// Code generated by ent, DO NOT EDIT.

package chargeflatfeeoverride

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/productcatalog"
	"github.com/openmeterio/openmeter/pkg/models"
)

const (
	// Label holds the string label denoting the chargeflatfeeoverride type in the database.
	Label = "charge_flat_fee_override"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldChargeID holds the string denoting the charge_id field in the database.
	FieldChargeID = "charge_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTaxBehavior holds the string denoting the tax_behavior field in the database.
	FieldTaxBehavior = "tax_behavior"
	// FieldTaxCodeID holds the string denoting the tax_code_id field in the database.
	FieldTaxCodeID = "tax_code_id"
	// FieldIntentDeletedAt holds the string denoting the intent_deleted_at field in the database.
	FieldIntentDeletedAt = "intent_deleted_at"
	// FieldServicePeriodFrom holds the string denoting the service_period_from field in the database.
	FieldServicePeriodFrom = "service_period_from"
	// FieldServicePeriodTo holds the string denoting the service_period_to field in the database.
	FieldServicePeriodTo = "service_period_to"
	// FieldFullServicePeriodFrom holds the string denoting the full_service_period_from field in the database.
	FieldFullServicePeriodFrom = "full_service_period_from"
	// FieldFullServicePeriodTo holds the string denoting the full_service_period_to field in the database.
	FieldFullServicePeriodTo = "full_service_period_to"
	// FieldBillingPeriodFrom holds the string denoting the billing_period_from field in the database.
	FieldBillingPeriodFrom = "billing_period_from"
	// FieldBillingPeriodTo holds the string denoting the billing_period_to field in the database.
	FieldBillingPeriodTo = "billing_period_to"
	// FieldFeatureKey holds the string denoting the feature_key field in the database.
	FieldFeatureKey = "feature_key"
	// FieldPaymentTerm holds the string denoting the payment_term field in the database.
	FieldPaymentTerm = "payment_term"
	// FieldProRating holds the string denoting the pro_rating field in the database.
	FieldProRating = "pro_rating"
	// FieldAmountBeforeProration holds the string denoting the amount_before_proration field in the database.
	FieldAmountBeforeProration = "amount_before_proration"
	// FieldPercentageDiscounts holds the string denoting the percentage_discounts field in the database.
	FieldPercentageDiscounts = "percentage_discounts"
	// EdgeFlatFee holds the string denoting the flat_fee edge name in mutations.
	EdgeFlatFee = "flat_fee"
	// EdgeTaxCode holds the string denoting the tax_code edge name in mutations.
	EdgeTaxCode = "tax_code"
	// Table holds the table name of the chargeflatfeeoverride in the database.
	Table = "charge_flat_fee_overrides"
	// FlatFeeTable is the table that holds the flat_fee relation/edge.
	FlatFeeTable = "charge_flat_fee_overrides"
	// FlatFeeInverseTable is the table name for the ChargeFlatFee entity.
	// It exists in this package in order to avoid circular dependency with the "chargeflatfee" package.
	FlatFeeInverseTable = "charge_flat_fees"
	// FlatFeeColumn is the table column denoting the flat_fee relation/edge.
	FlatFeeColumn = "charge_id"
	// TaxCodeTable is the table that holds the tax_code relation/edge.
	TaxCodeTable = "charge_flat_fee_overrides"
	// TaxCodeInverseTable is the table name for the TaxCode entity.
	// It exists in this package in order to avoid circular dependency with the "dbtaxcode" package.
	TaxCodeInverseTable = "tax_codes"
	// TaxCodeColumn is the table column denoting the tax_code relation/edge.
	TaxCodeColumn = "tax_code_id"
)

// Columns holds all SQL columns for chargeflatfeeoverride fields.
var Columns = []string{
	FieldID,
	FieldNamespace,
	FieldChargeID,
	FieldName,
	FieldDescription,
	FieldMetadata,
	FieldTaxBehavior,
	FieldTaxCodeID,
	FieldIntentDeletedAt,
	FieldServicePeriodFrom,
	FieldServicePeriodTo,
	FieldFullServicePeriodFrom,
	FieldFullServicePeriodTo,
	FieldBillingPeriodFrom,
	FieldBillingPeriodTo,
	FieldFeatureKey,
	FieldPaymentTerm,
	FieldProRating,
	FieldAmountBeforeProration,
	FieldPercentageDiscounts,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NamespaceValidator is a validator for the "namespace" field. It is called by the builders before save.
	NamespaceValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// FeatureKeyValidator is a validator for the "feature_key" field. It is called by the builders before save.
	FeatureKeyValidator func(string) error
	// PaymentTermValidator is a validator for the "payment_term" field. It is called by the builders before save.
	PaymentTermValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// ValueScanner of all ChargeFlatFeeOverride fields.
	ValueScanner struct {
		Metadata            field.TypeValueScanner[*models.Metadata]
		ProRating           field.TypeValueScanner[*productcatalog.ProRatingConfig]
		PercentageDiscounts field.TypeValueScanner[*productcatalog.PercentageDiscount]
	}
)

// OrderOption defines the ordering options for the ChargeFlatFeeOverride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByChargeID orders the results by the charge_id field.
func ByChargeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargeID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMetadata orders the results by the metadata field.
func ByMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadata, opts...).ToFunc()
}

// ByTaxBehavior orders the results by the tax_behavior field.
func ByTaxBehavior(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxBehavior, opts...).ToFunc()
}

// ByTaxCodeID orders the results by the tax_code_id field.
func ByTaxCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxCodeID, opts...).ToFunc()
}

// ByIntentDeletedAt orders the results by the intent_deleted_at field.
func ByIntentDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntentDeletedAt, opts...).ToFunc()
}

// ByServicePeriodFrom orders the results by the service_period_from field.
func ByServicePeriodFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServicePeriodFrom, opts...).ToFunc()
}

// ByServicePeriodTo orders the results by the service_period_to field.
func ByServicePeriodTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServicePeriodTo, opts...).ToFunc()
}

// ByFullServicePeriodFrom orders the results by the full_service_period_from field.
func ByFullServicePeriodFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullServicePeriodFrom, opts...).ToFunc()
}

// ByFullServicePeriodTo orders the results by the full_service_period_to field.
func ByFullServicePeriodTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullServicePeriodTo, opts...).ToFunc()
}

// ByBillingPeriodFrom orders the results by the billing_period_from field.
func ByBillingPeriodFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingPeriodFrom, opts...).ToFunc()
}

// ByBillingPeriodTo orders the results by the billing_period_to field.
func ByBillingPeriodTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingPeriodTo, opts...).ToFunc()
}

// ByFeatureKey orders the results by the feature_key field.
func ByFeatureKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatureKey, opts...).ToFunc()
}

// ByPaymentTerm orders the results by the payment_term field.
func ByPaymentTerm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentTerm, opts...).ToFunc()
}

// ByProRating orders the results by the pro_rating field.
func ByProRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProRating, opts...).ToFunc()
}

// ByAmountBeforeProration orders the results by the amount_before_proration field.
func ByAmountBeforeProration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountBeforeProration, opts...).ToFunc()
}

// ByPercentageDiscounts orders the results by the percentage_discounts field.
func ByPercentageDiscounts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPercentageDiscounts, opts...).ToFunc()
}

// ByFlatFeeField orders the results by flat_fee field.
func ByFlatFeeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlatFeeStep(), sql.OrderByField(field, opts...))
	}
}

// ByTaxCodeField orders the results by tax_code field.
func ByTaxCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaxCodeStep(), sql.OrderByField(field, opts...))
	}
}
func newFlatFeeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlatFeeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, FlatFeeTable, FlatFeeColumn),
	)
}
func newTaxCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaxCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaxCodeTable, TaxCodeColumn),
	)
}
