// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openmeterio/openmeter/openmeter/ent/db/billinginvoiceusagebasedlineconfig"
	"github.com/openmeterio/openmeter/openmeter/productcatalog/plan"
)

// BillingInvoiceUsageBasedLineConfig is the model entity for the BillingInvoiceUsageBasedLineConfig schema.
type BillingInvoiceUsageBasedLineConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// PriceType holds the value of the "price_type" field.
	PriceType plan.PriceType `json:"price_type,omitempty"`
	// FeatureKey holds the value of the "feature_key" field.
	FeatureKey string `json:"feature_key,omitempty"`
	// Price holds the value of the "price" field.
	Price        *plan.Price `json:"price,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingInvoiceUsageBasedLineConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billinginvoiceusagebasedlineconfig.FieldID, billinginvoiceusagebasedlineconfig.FieldNamespace, billinginvoiceusagebasedlineconfig.FieldPriceType, billinginvoiceusagebasedlineconfig.FieldFeatureKey:
			values[i] = new(sql.NullString)
		case billinginvoiceusagebasedlineconfig.FieldPrice:
			values[i] = billinginvoiceusagebasedlineconfig.ValueScanner.Price.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingInvoiceUsageBasedLineConfig fields.
func (biublc *BillingInvoiceUsageBasedLineConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billinginvoiceusagebasedlineconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				biublc.ID = value.String
			}
		case billinginvoiceusagebasedlineconfig.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				biublc.Namespace = value.String
			}
		case billinginvoiceusagebasedlineconfig.FieldPriceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_type", values[i])
			} else if value.Valid {
				biublc.PriceType = plan.PriceType(value.String)
			}
		case billinginvoiceusagebasedlineconfig.FieldFeatureKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature_key", values[i])
			} else if value.Valid {
				biublc.FeatureKey = value.String
			}
		case billinginvoiceusagebasedlineconfig.FieldPrice:
			if value, err := billinginvoiceusagebasedlineconfig.ValueScanner.Price.FromValue(values[i]); err != nil {
				return err
			} else {
				biublc.Price = value
			}
		default:
			biublc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingInvoiceUsageBasedLineConfig.
// This includes values selected through modifiers, order, etc.
func (biublc *BillingInvoiceUsageBasedLineConfig) Value(name string) (ent.Value, error) {
	return biublc.selectValues.Get(name)
}

// Update returns a builder for updating this BillingInvoiceUsageBasedLineConfig.
// Note that you need to call BillingInvoiceUsageBasedLineConfig.Unwrap() before calling this method if this BillingInvoiceUsageBasedLineConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (biublc *BillingInvoiceUsageBasedLineConfig) Update() *BillingInvoiceUsageBasedLineConfigUpdateOne {
	return NewBillingInvoiceUsageBasedLineConfigClient(biublc.config).UpdateOne(biublc)
}

// Unwrap unwraps the BillingInvoiceUsageBasedLineConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (biublc *BillingInvoiceUsageBasedLineConfig) Unwrap() *BillingInvoiceUsageBasedLineConfig {
	_tx, ok := biublc.config.driver.(*txDriver)
	if !ok {
		panic("db: BillingInvoiceUsageBasedLineConfig is not a transactional entity")
	}
	biublc.config.driver = _tx.drv
	return biublc
}

// String implements the fmt.Stringer.
func (biublc *BillingInvoiceUsageBasedLineConfig) String() string {
	var builder strings.Builder
	builder.WriteString("BillingInvoiceUsageBasedLineConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", biublc.ID))
	builder.WriteString("namespace=")
	builder.WriteString(biublc.Namespace)
	builder.WriteString(", ")
	builder.WriteString("price_type=")
	builder.WriteString(fmt.Sprintf("%v", biublc.PriceType))
	builder.WriteString(", ")
	builder.WriteString("feature_key=")
	builder.WriteString(biublc.FeatureKey)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", biublc.Price))
	builder.WriteByte(')')
	return builder.String()
}

// BillingInvoiceUsageBasedLineConfigs is a parsable slice of BillingInvoiceUsageBasedLineConfig.
type BillingInvoiceUsageBasedLineConfigs []*BillingInvoiceUsageBasedLineConfig
