// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/alpacahq/alpacadecimal"
	"github.com/openmeterio/openmeter/openmeter/billing"
	"github.com/openmeterio/openmeter/openmeter/billing/charges/creditpurchase"
	"github.com/openmeterio/openmeter/openmeter/billing/charges/meta"
	"github.com/openmeterio/openmeter/openmeter/ent/db/charge"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargecreditpurchase"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargecreditpurchaseexternalpayment"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargecreditpurchaseinvoicedpayment"
	"github.com/openmeterio/openmeter/openmeter/ent/db/customer"
	"github.com/openmeterio/openmeter/openmeter/ent/db/subscription"
	"github.com/openmeterio/openmeter/openmeter/ent/db/subscriptionitem"
	"github.com/openmeterio/openmeter/openmeter/ent/db/subscriptionphase"
	"github.com/openmeterio/openmeter/pkg/currencyx"
	"github.com/openmeterio/openmeter/pkg/models"
)

// ChargeCreditPurchaseCreate is the builder for creating a ChargeCreditPurchase entity.
type ChargeCreditPurchaseCreate struct {
	config
	mutation *ChargeCreditPurchaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCustomerID sets the "customer_id" field.
func (_c *ChargeCreditPurchaseCreate) SetCustomerID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetServicePeriodFrom sets the "service_period_from" field.
func (_c *ChargeCreditPurchaseCreate) SetServicePeriodFrom(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetServicePeriodFrom(v)
	return _c
}

// SetServicePeriodTo sets the "service_period_to" field.
func (_c *ChargeCreditPurchaseCreate) SetServicePeriodTo(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetServicePeriodTo(v)
	return _c
}

// SetBillingPeriodFrom sets the "billing_period_from" field.
func (_c *ChargeCreditPurchaseCreate) SetBillingPeriodFrom(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetBillingPeriodFrom(v)
	return _c
}

// SetBillingPeriodTo sets the "billing_period_to" field.
func (_c *ChargeCreditPurchaseCreate) SetBillingPeriodTo(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetBillingPeriodTo(v)
	return _c
}

// SetFullServicePeriodFrom sets the "full_service_period_from" field.
func (_c *ChargeCreditPurchaseCreate) SetFullServicePeriodFrom(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetFullServicePeriodFrom(v)
	return _c
}

// SetFullServicePeriodTo sets the "full_service_period_to" field.
func (_c *ChargeCreditPurchaseCreate) SetFullServicePeriodTo(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetFullServicePeriodTo(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChargeCreditPurchaseCreate) SetStatus(v meta.ChargeStatus) *ChargeCreditPurchaseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetUniqueReferenceID sets the "unique_reference_id" field.
func (_c *ChargeCreditPurchaseCreate) SetUniqueReferenceID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetUniqueReferenceID(v)
	return _c
}

// SetNillableUniqueReferenceID sets the "unique_reference_id" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableUniqueReferenceID(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetUniqueReferenceID(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ChargeCreditPurchaseCreate) SetCurrency(v currencyx.Code) *ChargeCreditPurchaseCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetManagedBy sets the "managed_by" field.
func (_c *ChargeCreditPurchaseCreate) SetManagedBy(v billing.InvoiceLineManagedBy) *ChargeCreditPurchaseCreate {
	_c.mutation.SetManagedBy(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *ChargeCreditPurchaseCreate) SetSubscriptionID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableSubscriptionID(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetSubscriptionPhaseID sets the "subscription_phase_id" field.
func (_c *ChargeCreditPurchaseCreate) SetSubscriptionPhaseID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetSubscriptionPhaseID(v)
	return _c
}

// SetNillableSubscriptionPhaseID sets the "subscription_phase_id" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableSubscriptionPhaseID(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetSubscriptionPhaseID(*v)
	}
	return _c
}

// SetSubscriptionItemID sets the "subscription_item_id" field.
func (_c *ChargeCreditPurchaseCreate) SetSubscriptionItemID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetSubscriptionItemID(v)
	return _c
}

// SetNillableSubscriptionItemID sets the "subscription_item_id" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableSubscriptionItemID(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetSubscriptionItemID(*v)
	}
	return _c
}

// SetAdvanceAfter sets the "advance_after" field.
func (_c *ChargeCreditPurchaseCreate) SetAdvanceAfter(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetAdvanceAfter(v)
	return _c
}

// SetNillableAdvanceAfter sets the "advance_after" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableAdvanceAfter(v *time.Time) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetAdvanceAfter(*v)
	}
	return _c
}

// SetAnnotations sets the "annotations" field.
func (_c *ChargeCreditPurchaseCreate) SetAnnotations(v models.Annotations) *ChargeCreditPurchaseCreate {
	_c.mutation.SetAnnotations(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *ChargeCreditPurchaseCreate) SetNamespace(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ChargeCreditPurchaseCreate) SetMetadata(v map[string]string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChargeCreditPurchaseCreate) SetCreatedAt(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableCreatedAt(v *time.Time) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChargeCreditPurchaseCreate) SetUpdatedAt(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableUpdatedAt(v *time.Time) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChargeCreditPurchaseCreate) SetDeletedAt(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableDeletedAt(v *time.Time) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ChargeCreditPurchaseCreate) SetName(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ChargeCreditPurchaseCreate) SetDescription(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableDescription(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreditAmount sets the "credit_amount" field.
func (_c *ChargeCreditPurchaseCreate) SetCreditAmount(v alpacadecimal.Decimal) *ChargeCreditPurchaseCreate {
	_c.mutation.SetCreditAmount(v)
	return _c
}

// SetSettlement sets the "settlement" field.
func (_c *ChargeCreditPurchaseCreate) SetSettlement(v creditpurchase.Settlement) *ChargeCreditPurchaseCreate {
	_c.mutation.SetSettlement(v)
	return _c
}

// SetCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field.
func (_c *ChargeCreditPurchaseCreate) SetCreditGrantTransactionGroupID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetCreditGrantTransactionGroupID(v)
	return _c
}

// SetNillableCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableCreditGrantTransactionGroupID(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetCreditGrantTransactionGroupID(*v)
	}
	return _c
}

// SetCreditGrantedAt sets the "credit_granted_at" field.
func (_c *ChargeCreditPurchaseCreate) SetCreditGrantedAt(v time.Time) *ChargeCreditPurchaseCreate {
	_c.mutation.SetCreditGrantedAt(v)
	return _c
}

// SetNillableCreditGrantedAt sets the "credit_granted_at" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableCreditGrantedAt(v *time.Time) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetCreditGrantedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChargeCreditPurchaseCreate) SetID(v string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableID(v *string) *ChargeCreditPurchaseCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetExternalPaymentID sets the "external_payment" edge to the ChargeCreditPurchaseExternalPayment entity by ID.
func (_c *ChargeCreditPurchaseCreate) SetExternalPaymentID(id string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetExternalPaymentID(id)
	return _c
}

// SetNillableExternalPaymentID sets the "external_payment" edge to the ChargeCreditPurchaseExternalPayment entity by ID if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableExternalPaymentID(id *string) *ChargeCreditPurchaseCreate {
	if id != nil {
		_c = _c.SetExternalPaymentID(*id)
	}
	return _c
}

// SetExternalPayment sets the "external_payment" edge to the ChargeCreditPurchaseExternalPayment entity.
func (_c *ChargeCreditPurchaseCreate) SetExternalPayment(v *ChargeCreditPurchaseExternalPayment) *ChargeCreditPurchaseCreate {
	return _c.SetExternalPaymentID(v.ID)
}

// SetInvoicedPaymentID sets the "invoiced_payment" edge to the ChargeCreditPurchaseInvoicedPayment entity by ID.
func (_c *ChargeCreditPurchaseCreate) SetInvoicedPaymentID(id string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetInvoicedPaymentID(id)
	return _c
}

// SetNillableInvoicedPaymentID sets the "invoiced_payment" edge to the ChargeCreditPurchaseInvoicedPayment entity by ID if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableInvoicedPaymentID(id *string) *ChargeCreditPurchaseCreate {
	if id != nil {
		_c = _c.SetInvoicedPaymentID(*id)
	}
	return _c
}

// SetInvoicedPayment sets the "invoiced_payment" edge to the ChargeCreditPurchaseInvoicedPayment entity.
func (_c *ChargeCreditPurchaseCreate) SetInvoicedPayment(v *ChargeCreditPurchaseInvoicedPayment) *ChargeCreditPurchaseCreate {
	return _c.SetInvoicedPaymentID(v.ID)
}

// SetChargeID sets the "charge" edge to the Charge entity by ID.
func (_c *ChargeCreditPurchaseCreate) SetChargeID(id string) *ChargeCreditPurchaseCreate {
	_c.mutation.SetChargeID(id)
	return _c
}

// SetNillableChargeID sets the "charge" edge to the Charge entity by ID if the given value is not nil.
func (_c *ChargeCreditPurchaseCreate) SetNillableChargeID(id *string) *ChargeCreditPurchaseCreate {
	if id != nil {
		_c = _c.SetChargeID(*id)
	}
	return _c
}

// SetCharge sets the "charge" edge to the Charge entity.
func (_c *ChargeCreditPurchaseCreate) SetCharge(v *Charge) *ChargeCreditPurchaseCreate {
	return _c.SetChargeID(v.ID)
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_c *ChargeCreditPurchaseCreate) SetSubscription(v *Subscription) *ChargeCreditPurchaseCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetSubscriptionPhase sets the "subscription_phase" edge to the SubscriptionPhase entity.
func (_c *ChargeCreditPurchaseCreate) SetSubscriptionPhase(v *SubscriptionPhase) *ChargeCreditPurchaseCreate {
	return _c.SetSubscriptionPhaseID(v.ID)
}

// SetSubscriptionItem sets the "subscription_item" edge to the SubscriptionItem entity.
func (_c *ChargeCreditPurchaseCreate) SetSubscriptionItem(v *SubscriptionItem) *ChargeCreditPurchaseCreate {
	return _c.SetSubscriptionItemID(v.ID)
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_c *ChargeCreditPurchaseCreate) SetCustomer(v *Customer) *ChargeCreditPurchaseCreate {
	return _c.SetCustomerID(v.ID)
}

// Mutation returns the ChargeCreditPurchaseMutation object of the builder.
func (_c *ChargeCreditPurchaseCreate) Mutation() *ChargeCreditPurchaseMutation {
	return _c.mutation
}

// Save creates the ChargeCreditPurchase in the database.
func (_c *ChargeCreditPurchaseCreate) Save(ctx context.Context) (*ChargeCreditPurchase, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChargeCreditPurchaseCreate) SaveX(ctx context.Context) *ChargeCreditPurchase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChargeCreditPurchaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChargeCreditPurchaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChargeCreditPurchaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chargecreditpurchase.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chargecreditpurchase.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chargecreditpurchase.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChargeCreditPurchaseCreate) check() error {
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`db: missing required field "ChargeCreditPurchase.customer_id"`)}
	}
	if v, ok := _c.mutation.CustomerID(); ok {
		if err := chargecreditpurchase.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.customer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServicePeriodFrom(); !ok {
		return &ValidationError{Name: "service_period_from", err: errors.New(`db: missing required field "ChargeCreditPurchase.service_period_from"`)}
	}
	if _, ok := _c.mutation.ServicePeriodTo(); !ok {
		return &ValidationError{Name: "service_period_to", err: errors.New(`db: missing required field "ChargeCreditPurchase.service_period_to"`)}
	}
	if _, ok := _c.mutation.BillingPeriodFrom(); !ok {
		return &ValidationError{Name: "billing_period_from", err: errors.New(`db: missing required field "ChargeCreditPurchase.billing_period_from"`)}
	}
	if _, ok := _c.mutation.BillingPeriodTo(); !ok {
		return &ValidationError{Name: "billing_period_to", err: errors.New(`db: missing required field "ChargeCreditPurchase.billing_period_to"`)}
	}
	if _, ok := _c.mutation.FullServicePeriodFrom(); !ok {
		return &ValidationError{Name: "full_service_period_from", err: errors.New(`db: missing required field "ChargeCreditPurchase.full_service_period_from"`)}
	}
	if _, ok := _c.mutation.FullServicePeriodTo(); !ok {
		return &ValidationError{Name: "full_service_period_to", err: errors.New(`db: missing required field "ChargeCreditPurchase.full_service_period_to"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "ChargeCreditPurchase.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := chargecreditpurchase.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`db: missing required field "ChargeCreditPurchase.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := chargecreditpurchase.CurrencyValidator(string(v)); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManagedBy(); !ok {
		return &ValidationError{Name: "managed_by", err: errors.New(`db: missing required field "ChargeCreditPurchase.managed_by"`)}
	}
	if v, ok := _c.mutation.ManagedBy(); ok {
		if err := chargecreditpurchase.ManagedByValidator(v); err != nil {
			return &ValidationError{Name: "managed_by", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.managed_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`db: missing required field "ChargeCreditPurchase.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := chargecreditpurchase.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "ChargeCreditPurchase.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "ChargeCreditPurchase.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "ChargeCreditPurchase.name"`)}
	}
	if _, ok := _c.mutation.CreditAmount(); !ok {
		return &ValidationError{Name: "credit_amount", err: errors.New(`db: missing required field "ChargeCreditPurchase.credit_amount"`)}
	}
	if _, ok := _c.mutation.Settlement(); !ok {
		return &ValidationError{Name: "settlement", err: errors.New(`db: missing required field "ChargeCreditPurchase.settlement"`)}
	}
	if v, ok := _c.mutation.Settlement(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "settlement", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.settlement": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CreditGrantTransactionGroupID(); ok {
		if err := chargecreditpurchase.CreditGrantTransactionGroupIDValidator(v); err != nil {
			return &ValidationError{Name: "credit_grant_transaction_group_id", err: fmt.Errorf(`db: validator failed for field "ChargeCreditPurchase.credit_grant_transaction_group_id": %w`, err)}
		}
	}
	if len(_c.mutation.CustomerIDs()) == 0 {
		return &ValidationError{Name: "customer", err: errors.New(`db: missing required edge "ChargeCreditPurchase.customer"`)}
	}
	return nil
}

func (_c *ChargeCreditPurchaseCreate) sqlSave(ctx context.Context) (*ChargeCreditPurchase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ChargeCreditPurchase.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChargeCreditPurchaseCreate) createSpec() (*ChargeCreditPurchase, *sqlgraph.CreateSpec, error) {
	var (
		_node = &ChargeCreditPurchase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chargecreditpurchase.Table, sqlgraph.NewFieldSpec(chargecreditpurchase.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ServicePeriodFrom(); ok {
		_spec.SetField(chargecreditpurchase.FieldServicePeriodFrom, field.TypeTime, value)
		_node.ServicePeriodFrom = value
	}
	if value, ok := _c.mutation.ServicePeriodTo(); ok {
		_spec.SetField(chargecreditpurchase.FieldServicePeriodTo, field.TypeTime, value)
		_node.ServicePeriodTo = value
	}
	if value, ok := _c.mutation.BillingPeriodFrom(); ok {
		_spec.SetField(chargecreditpurchase.FieldBillingPeriodFrom, field.TypeTime, value)
		_node.BillingPeriodFrom = value
	}
	if value, ok := _c.mutation.BillingPeriodTo(); ok {
		_spec.SetField(chargecreditpurchase.FieldBillingPeriodTo, field.TypeTime, value)
		_node.BillingPeriodTo = value
	}
	if value, ok := _c.mutation.FullServicePeriodFrom(); ok {
		_spec.SetField(chargecreditpurchase.FieldFullServicePeriodFrom, field.TypeTime, value)
		_node.FullServicePeriodFrom = value
	}
	if value, ok := _c.mutation.FullServicePeriodTo(); ok {
		_spec.SetField(chargecreditpurchase.FieldFullServicePeriodTo, field.TypeTime, value)
		_node.FullServicePeriodTo = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chargecreditpurchase.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UniqueReferenceID(); ok {
		_spec.SetField(chargecreditpurchase.FieldUniqueReferenceID, field.TypeString, value)
		_node.UniqueReferenceID = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(chargecreditpurchase.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ManagedBy(); ok {
		_spec.SetField(chargecreditpurchase.FieldManagedBy, field.TypeEnum, value)
		_node.ManagedBy = value
	}
	if value, ok := _c.mutation.AdvanceAfter(); ok {
		_spec.SetField(chargecreditpurchase.FieldAdvanceAfter, field.TypeTime, value)
		_node.AdvanceAfter = &value
	}
	if value, ok := _c.mutation.Annotations(); ok {
		_spec.SetField(chargecreditpurchase.FieldAnnotations, field.TypeJSON, value)
		_node.Annotations = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(chargecreditpurchase.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(chargecreditpurchase.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chargecreditpurchase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chargecreditpurchase.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(chargecreditpurchase.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chargecreditpurchase.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(chargecreditpurchase.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.CreditAmount(); ok {
		_spec.SetField(chargecreditpurchase.FieldCreditAmount, field.TypeOther, value)
		_node.CreditAmount = value
	}
	if value, ok := _c.mutation.Settlement(); ok {
		vv, err := chargecreditpurchase.ValueScanner.Settlement.Value(value)
		if err != nil {
			return nil, nil, err
		}
		_spec.SetField(chargecreditpurchase.FieldSettlement, field.TypeString, vv)
		_node.Settlement = value
	}
	if value, ok := _c.mutation.CreditGrantTransactionGroupID(); ok {
		_spec.SetField(chargecreditpurchase.FieldCreditGrantTransactionGroupID, field.TypeString, value)
		_node.CreditGrantTransactionGroupID = &value
	}
	if value, ok := _c.mutation.CreditGrantedAt(); ok {
		_spec.SetField(chargecreditpurchase.FieldCreditGrantedAt, field.TypeTime, value)
		_node.CreditGrantedAt = &value
	}
	if nodes := _c.mutation.ExternalPaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chargecreditpurchase.ExternalPaymentTable,
			Columns: []string{chargecreditpurchase.ExternalPaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chargecreditpurchaseexternalpayment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvoicedPaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chargecreditpurchase.InvoicedPaymentTable,
			Columns: []string{chargecreditpurchase.InvoicedPaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chargecreditpurchaseinvoicedpayment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChargeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chargecreditpurchase.ChargeTable,
			Columns: []string{chargecreditpurchase.ChargeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(charge.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chargecreditpurchase.SubscriptionTable,
			Columns: []string{chargecreditpurchase.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionPhaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chargecreditpurchase.SubscriptionPhaseTable,
			Columns: []string{chargecreditpurchase.SubscriptionPhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionPhaseID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chargecreditpurchase.SubscriptionItemTable,
			Columns: []string{chargecreditpurchase.SubscriptionItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionItemID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chargecreditpurchase.CustomerTable,
			Columns: []string{chargecreditpurchase.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChargeCreditPurchase.Create().
//		SetCustomerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChargeCreditPurchaseUpsert) {
//			SetCustomerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChargeCreditPurchaseCreate) OnConflict(opts ...sql.ConflictOption) *ChargeCreditPurchaseUpsertOne {
	_c.conflict = opts
	return &ChargeCreditPurchaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChargeCreditPurchase.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChargeCreditPurchaseCreate) OnConflictColumns(columns ...string) *ChargeCreditPurchaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChargeCreditPurchaseUpsertOne{
		create: _c,
	}
}

type (
	// ChargeCreditPurchaseUpsertOne is the builder for "upsert"-ing
	//  one ChargeCreditPurchase node.
	ChargeCreditPurchaseUpsertOne struct {
		create *ChargeCreditPurchaseCreate
	}

	// ChargeCreditPurchaseUpsert is the "OnConflict" setter.
	ChargeCreditPurchaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetServicePeriodFrom sets the "service_period_from" field.
func (u *ChargeCreditPurchaseUpsert) SetServicePeriodFrom(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldServicePeriodFrom, v)
	return u
}

// UpdateServicePeriodFrom sets the "service_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateServicePeriodFrom() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldServicePeriodFrom)
	return u
}

// SetServicePeriodTo sets the "service_period_to" field.
func (u *ChargeCreditPurchaseUpsert) SetServicePeriodTo(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldServicePeriodTo, v)
	return u
}

// UpdateServicePeriodTo sets the "service_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateServicePeriodTo() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldServicePeriodTo)
	return u
}

// SetBillingPeriodFrom sets the "billing_period_from" field.
func (u *ChargeCreditPurchaseUpsert) SetBillingPeriodFrom(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldBillingPeriodFrom, v)
	return u
}

// UpdateBillingPeriodFrom sets the "billing_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateBillingPeriodFrom() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldBillingPeriodFrom)
	return u
}

// SetBillingPeriodTo sets the "billing_period_to" field.
func (u *ChargeCreditPurchaseUpsert) SetBillingPeriodTo(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldBillingPeriodTo, v)
	return u
}

// UpdateBillingPeriodTo sets the "billing_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateBillingPeriodTo() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldBillingPeriodTo)
	return u
}

// SetFullServicePeriodFrom sets the "full_service_period_from" field.
func (u *ChargeCreditPurchaseUpsert) SetFullServicePeriodFrom(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldFullServicePeriodFrom, v)
	return u
}

// UpdateFullServicePeriodFrom sets the "full_service_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateFullServicePeriodFrom() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldFullServicePeriodFrom)
	return u
}

// SetFullServicePeriodTo sets the "full_service_period_to" field.
func (u *ChargeCreditPurchaseUpsert) SetFullServicePeriodTo(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldFullServicePeriodTo, v)
	return u
}

// UpdateFullServicePeriodTo sets the "full_service_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateFullServicePeriodTo() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldFullServicePeriodTo)
	return u
}

// SetStatus sets the "status" field.
func (u *ChargeCreditPurchaseUpsert) SetStatus(v meta.ChargeStatus) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateStatus() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldStatus)
	return u
}

// SetManagedBy sets the "managed_by" field.
func (u *ChargeCreditPurchaseUpsert) SetManagedBy(v billing.InvoiceLineManagedBy) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldManagedBy, v)
	return u
}

// UpdateManagedBy sets the "managed_by" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateManagedBy() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldManagedBy)
	return u
}

// SetAdvanceAfter sets the "advance_after" field.
func (u *ChargeCreditPurchaseUpsert) SetAdvanceAfter(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldAdvanceAfter, v)
	return u
}

// UpdateAdvanceAfter sets the "advance_after" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateAdvanceAfter() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldAdvanceAfter)
	return u
}

// ClearAdvanceAfter clears the value of the "advance_after" field.
func (u *ChargeCreditPurchaseUpsert) ClearAdvanceAfter() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldAdvanceAfter)
	return u
}

// SetAnnotations sets the "annotations" field.
func (u *ChargeCreditPurchaseUpsert) SetAnnotations(v models.Annotations) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldAnnotations, v)
	return u
}

// UpdateAnnotations sets the "annotations" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateAnnotations() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldAnnotations)
	return u
}

// ClearAnnotations clears the value of the "annotations" field.
func (u *ChargeCreditPurchaseUpsert) ClearAnnotations() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldAnnotations)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ChargeCreditPurchaseUpsert) SetMetadata(v map[string]string) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateMetadata() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChargeCreditPurchaseUpsert) ClearMetadata() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChargeCreditPurchaseUpsert) SetUpdatedAt(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateUpdatedAt() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChargeCreditPurchaseUpsert) SetDeletedAt(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateDeletedAt() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChargeCreditPurchaseUpsert) ClearDeletedAt() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *ChargeCreditPurchaseUpsert) SetName(v string) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateName() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ChargeCreditPurchaseUpsert) SetDescription(v string) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateDescription() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ChargeCreditPurchaseUpsert) ClearDescription() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldDescription)
	return u
}

// SetCreditAmount sets the "credit_amount" field.
func (u *ChargeCreditPurchaseUpsert) SetCreditAmount(v alpacadecimal.Decimal) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldCreditAmount, v)
	return u
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateCreditAmount() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldCreditAmount)
	return u
}

// SetSettlement sets the "settlement" field.
func (u *ChargeCreditPurchaseUpsert) SetSettlement(v creditpurchase.Settlement) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldSettlement, v)
	return u
}

// UpdateSettlement sets the "settlement" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateSettlement() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldSettlement)
	return u
}

// SetCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field.
func (u *ChargeCreditPurchaseUpsert) SetCreditGrantTransactionGroupID(v string) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldCreditGrantTransactionGroupID, v)
	return u
}

// UpdateCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateCreditGrantTransactionGroupID() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldCreditGrantTransactionGroupID)
	return u
}

// ClearCreditGrantTransactionGroupID clears the value of the "credit_grant_transaction_group_id" field.
func (u *ChargeCreditPurchaseUpsert) ClearCreditGrantTransactionGroupID() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldCreditGrantTransactionGroupID)
	return u
}

// SetCreditGrantedAt sets the "credit_granted_at" field.
func (u *ChargeCreditPurchaseUpsert) SetCreditGrantedAt(v time.Time) *ChargeCreditPurchaseUpsert {
	u.Set(chargecreditpurchase.FieldCreditGrantedAt, v)
	return u
}

// UpdateCreditGrantedAt sets the "credit_granted_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsert) UpdateCreditGrantedAt() *ChargeCreditPurchaseUpsert {
	u.SetExcluded(chargecreditpurchase.FieldCreditGrantedAt)
	return u
}

// ClearCreditGrantedAt clears the value of the "credit_granted_at" field.
func (u *ChargeCreditPurchaseUpsert) ClearCreditGrantedAt() *ChargeCreditPurchaseUpsert {
	u.SetNull(chargecreditpurchase.FieldCreditGrantedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ChargeCreditPurchase.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chargecreditpurchase.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChargeCreditPurchaseUpsertOne) UpdateNewValues() *ChargeCreditPurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(chargecreditpurchase.FieldID)
		}
		if _, exists := u.create.mutation.CustomerID(); exists {
			s.SetIgnore(chargecreditpurchase.FieldCustomerID)
		}
		if _, exists := u.create.mutation.UniqueReferenceID(); exists {
			s.SetIgnore(chargecreditpurchase.FieldUniqueReferenceID)
		}
		if _, exists := u.create.mutation.Currency(); exists {
			s.SetIgnore(chargecreditpurchase.FieldCurrency)
		}
		if _, exists := u.create.mutation.SubscriptionID(); exists {
			s.SetIgnore(chargecreditpurchase.FieldSubscriptionID)
		}
		if _, exists := u.create.mutation.SubscriptionPhaseID(); exists {
			s.SetIgnore(chargecreditpurchase.FieldSubscriptionPhaseID)
		}
		if _, exists := u.create.mutation.SubscriptionItemID(); exists {
			s.SetIgnore(chargecreditpurchase.FieldSubscriptionItemID)
		}
		if _, exists := u.create.mutation.Namespace(); exists {
			s.SetIgnore(chargecreditpurchase.FieldNamespace)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chargecreditpurchase.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChargeCreditPurchase.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChargeCreditPurchaseUpsertOne) Ignore() *ChargeCreditPurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChargeCreditPurchaseUpsertOne) DoNothing() *ChargeCreditPurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChargeCreditPurchaseCreate.OnConflict
// documentation for more info.
func (u *ChargeCreditPurchaseUpsertOne) Update(set func(*ChargeCreditPurchaseUpsert)) *ChargeCreditPurchaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChargeCreditPurchaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetServicePeriodFrom sets the "service_period_from" field.
func (u *ChargeCreditPurchaseUpsertOne) SetServicePeriodFrom(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetServicePeriodFrom(v)
	})
}

// UpdateServicePeriodFrom sets the "service_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateServicePeriodFrom() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateServicePeriodFrom()
	})
}

// SetServicePeriodTo sets the "service_period_to" field.
func (u *ChargeCreditPurchaseUpsertOne) SetServicePeriodTo(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetServicePeriodTo(v)
	})
}

// UpdateServicePeriodTo sets the "service_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateServicePeriodTo() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateServicePeriodTo()
	})
}

// SetBillingPeriodFrom sets the "billing_period_from" field.
func (u *ChargeCreditPurchaseUpsertOne) SetBillingPeriodFrom(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetBillingPeriodFrom(v)
	})
}

// UpdateBillingPeriodFrom sets the "billing_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateBillingPeriodFrom() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateBillingPeriodFrom()
	})
}

// SetBillingPeriodTo sets the "billing_period_to" field.
func (u *ChargeCreditPurchaseUpsertOne) SetBillingPeriodTo(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetBillingPeriodTo(v)
	})
}

// UpdateBillingPeriodTo sets the "billing_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateBillingPeriodTo() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateBillingPeriodTo()
	})
}

// SetFullServicePeriodFrom sets the "full_service_period_from" field.
func (u *ChargeCreditPurchaseUpsertOne) SetFullServicePeriodFrom(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetFullServicePeriodFrom(v)
	})
}

// UpdateFullServicePeriodFrom sets the "full_service_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateFullServicePeriodFrom() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateFullServicePeriodFrom()
	})
}

// SetFullServicePeriodTo sets the "full_service_period_to" field.
func (u *ChargeCreditPurchaseUpsertOne) SetFullServicePeriodTo(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetFullServicePeriodTo(v)
	})
}

// UpdateFullServicePeriodTo sets the "full_service_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateFullServicePeriodTo() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateFullServicePeriodTo()
	})
}

// SetStatus sets the "status" field.
func (u *ChargeCreditPurchaseUpsertOne) SetStatus(v meta.ChargeStatus) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateStatus() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateStatus()
	})
}

// SetManagedBy sets the "managed_by" field.
func (u *ChargeCreditPurchaseUpsertOne) SetManagedBy(v billing.InvoiceLineManagedBy) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetManagedBy(v)
	})
}

// UpdateManagedBy sets the "managed_by" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateManagedBy() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateManagedBy()
	})
}

// SetAdvanceAfter sets the "advance_after" field.
func (u *ChargeCreditPurchaseUpsertOne) SetAdvanceAfter(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetAdvanceAfter(v)
	})
}

// UpdateAdvanceAfter sets the "advance_after" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateAdvanceAfter() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateAdvanceAfter()
	})
}

// ClearAdvanceAfter clears the value of the "advance_after" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearAdvanceAfter() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearAdvanceAfter()
	})
}

// SetAnnotations sets the "annotations" field.
func (u *ChargeCreditPurchaseUpsertOne) SetAnnotations(v models.Annotations) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetAnnotations(v)
	})
}

// UpdateAnnotations sets the "annotations" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateAnnotations() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateAnnotations()
	})
}

// ClearAnnotations clears the value of the "annotations" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearAnnotations() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearAnnotations()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChargeCreditPurchaseUpsertOne) SetMetadata(v map[string]string) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateMetadata() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearMetadata() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChargeCreditPurchaseUpsertOne) SetUpdatedAt(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateUpdatedAt() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChargeCreditPurchaseUpsertOne) SetDeletedAt(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateDeletedAt() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearDeletedAt() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ChargeCreditPurchaseUpsertOne) SetName(v string) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateName() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ChargeCreditPurchaseUpsertOne) SetDescription(v string) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateDescription() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearDescription() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearDescription()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *ChargeCreditPurchaseUpsertOne) SetCreditAmount(v alpacadecimal.Decimal) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateCreditAmount() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateCreditAmount()
	})
}

// SetSettlement sets the "settlement" field.
func (u *ChargeCreditPurchaseUpsertOne) SetSettlement(v creditpurchase.Settlement) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetSettlement(v)
	})
}

// UpdateSettlement sets the "settlement" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateSettlement() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateSettlement()
	})
}

// SetCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field.
func (u *ChargeCreditPurchaseUpsertOne) SetCreditGrantTransactionGroupID(v string) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetCreditGrantTransactionGroupID(v)
	})
}

// UpdateCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateCreditGrantTransactionGroupID() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateCreditGrantTransactionGroupID()
	})
}

// ClearCreditGrantTransactionGroupID clears the value of the "credit_grant_transaction_group_id" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearCreditGrantTransactionGroupID() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearCreditGrantTransactionGroupID()
	})
}

// SetCreditGrantedAt sets the "credit_granted_at" field.
func (u *ChargeCreditPurchaseUpsertOne) SetCreditGrantedAt(v time.Time) *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetCreditGrantedAt(v)
	})
}

// UpdateCreditGrantedAt sets the "credit_granted_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertOne) UpdateCreditGrantedAt() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateCreditGrantedAt()
	})
}

// ClearCreditGrantedAt clears the value of the "credit_granted_at" field.
func (u *ChargeCreditPurchaseUpsertOne) ClearCreditGrantedAt() *ChargeCreditPurchaseUpsertOne {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearCreditGrantedAt()
	})
}

// Exec executes the query.
func (u *ChargeCreditPurchaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ChargeCreditPurchaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChargeCreditPurchaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChargeCreditPurchaseUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: ChargeCreditPurchaseUpsertOne.ID is not supported by MySQL driver. Use ChargeCreditPurchaseUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChargeCreditPurchaseUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChargeCreditPurchaseCreateBulk is the builder for creating many ChargeCreditPurchase entities in bulk.
type ChargeCreditPurchaseCreateBulk struct {
	config
	err      error
	builders []*ChargeCreditPurchaseCreate
	conflict []sql.ConflictOption
}

// Save creates the ChargeCreditPurchase entities in the database.
func (_c *ChargeCreditPurchaseCreateBulk) Save(ctx context.Context) ([]*ChargeCreditPurchase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChargeCreditPurchase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChargeCreditPurchaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChargeCreditPurchaseCreateBulk) SaveX(ctx context.Context) []*ChargeCreditPurchase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChargeCreditPurchaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChargeCreditPurchaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChargeCreditPurchase.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChargeCreditPurchaseUpsert) {
//			SetCustomerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChargeCreditPurchaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChargeCreditPurchaseUpsertBulk {
	_c.conflict = opts
	return &ChargeCreditPurchaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChargeCreditPurchase.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChargeCreditPurchaseCreateBulk) OnConflictColumns(columns ...string) *ChargeCreditPurchaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChargeCreditPurchaseUpsertBulk{
		create: _c,
	}
}

// ChargeCreditPurchaseUpsertBulk is the builder for "upsert"-ing
// a bulk of ChargeCreditPurchase nodes.
type ChargeCreditPurchaseUpsertBulk struct {
	create *ChargeCreditPurchaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChargeCreditPurchase.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chargecreditpurchase.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChargeCreditPurchaseUpsertBulk) UpdateNewValues() *ChargeCreditPurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(chargecreditpurchase.FieldID)
			}
			if _, exists := b.mutation.CustomerID(); exists {
				s.SetIgnore(chargecreditpurchase.FieldCustomerID)
			}
			if _, exists := b.mutation.UniqueReferenceID(); exists {
				s.SetIgnore(chargecreditpurchase.FieldUniqueReferenceID)
			}
			if _, exists := b.mutation.Currency(); exists {
				s.SetIgnore(chargecreditpurchase.FieldCurrency)
			}
			if _, exists := b.mutation.SubscriptionID(); exists {
				s.SetIgnore(chargecreditpurchase.FieldSubscriptionID)
			}
			if _, exists := b.mutation.SubscriptionPhaseID(); exists {
				s.SetIgnore(chargecreditpurchase.FieldSubscriptionPhaseID)
			}
			if _, exists := b.mutation.SubscriptionItemID(); exists {
				s.SetIgnore(chargecreditpurchase.FieldSubscriptionItemID)
			}
			if _, exists := b.mutation.Namespace(); exists {
				s.SetIgnore(chargecreditpurchase.FieldNamespace)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chargecreditpurchase.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChargeCreditPurchase.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChargeCreditPurchaseUpsertBulk) Ignore() *ChargeCreditPurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChargeCreditPurchaseUpsertBulk) DoNothing() *ChargeCreditPurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChargeCreditPurchaseCreateBulk.OnConflict
// documentation for more info.
func (u *ChargeCreditPurchaseUpsertBulk) Update(set func(*ChargeCreditPurchaseUpsert)) *ChargeCreditPurchaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChargeCreditPurchaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetServicePeriodFrom sets the "service_period_from" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetServicePeriodFrom(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetServicePeriodFrom(v)
	})
}

// UpdateServicePeriodFrom sets the "service_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateServicePeriodFrom() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateServicePeriodFrom()
	})
}

// SetServicePeriodTo sets the "service_period_to" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetServicePeriodTo(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetServicePeriodTo(v)
	})
}

// UpdateServicePeriodTo sets the "service_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateServicePeriodTo() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateServicePeriodTo()
	})
}

// SetBillingPeriodFrom sets the "billing_period_from" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetBillingPeriodFrom(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetBillingPeriodFrom(v)
	})
}

// UpdateBillingPeriodFrom sets the "billing_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateBillingPeriodFrom() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateBillingPeriodFrom()
	})
}

// SetBillingPeriodTo sets the "billing_period_to" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetBillingPeriodTo(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetBillingPeriodTo(v)
	})
}

// UpdateBillingPeriodTo sets the "billing_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateBillingPeriodTo() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateBillingPeriodTo()
	})
}

// SetFullServicePeriodFrom sets the "full_service_period_from" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetFullServicePeriodFrom(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetFullServicePeriodFrom(v)
	})
}

// UpdateFullServicePeriodFrom sets the "full_service_period_from" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateFullServicePeriodFrom() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateFullServicePeriodFrom()
	})
}

// SetFullServicePeriodTo sets the "full_service_period_to" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetFullServicePeriodTo(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetFullServicePeriodTo(v)
	})
}

// UpdateFullServicePeriodTo sets the "full_service_period_to" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateFullServicePeriodTo() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateFullServicePeriodTo()
	})
}

// SetStatus sets the "status" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetStatus(v meta.ChargeStatus) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateStatus() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateStatus()
	})
}

// SetManagedBy sets the "managed_by" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetManagedBy(v billing.InvoiceLineManagedBy) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetManagedBy(v)
	})
}

// UpdateManagedBy sets the "managed_by" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateManagedBy() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateManagedBy()
	})
}

// SetAdvanceAfter sets the "advance_after" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetAdvanceAfter(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetAdvanceAfter(v)
	})
}

// UpdateAdvanceAfter sets the "advance_after" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateAdvanceAfter() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateAdvanceAfter()
	})
}

// ClearAdvanceAfter clears the value of the "advance_after" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearAdvanceAfter() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearAdvanceAfter()
	})
}

// SetAnnotations sets the "annotations" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetAnnotations(v models.Annotations) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetAnnotations(v)
	})
}

// UpdateAnnotations sets the "annotations" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateAnnotations() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateAnnotations()
	})
}

// ClearAnnotations clears the value of the "annotations" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearAnnotations() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearAnnotations()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetMetadata(v map[string]string) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateMetadata() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearMetadata() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetUpdatedAt(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateUpdatedAt() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetDeletedAt(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateDeletedAt() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearDeletedAt() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetName(v string) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateName() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetDescription(v string) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateDescription() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearDescription() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearDescription()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetCreditAmount(v alpacadecimal.Decimal) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateCreditAmount() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateCreditAmount()
	})
}

// SetSettlement sets the "settlement" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetSettlement(v creditpurchase.Settlement) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetSettlement(v)
	})
}

// UpdateSettlement sets the "settlement" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateSettlement() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateSettlement()
	})
}

// SetCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetCreditGrantTransactionGroupID(v string) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetCreditGrantTransactionGroupID(v)
	})
}

// UpdateCreditGrantTransactionGroupID sets the "credit_grant_transaction_group_id" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateCreditGrantTransactionGroupID() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateCreditGrantTransactionGroupID()
	})
}

// ClearCreditGrantTransactionGroupID clears the value of the "credit_grant_transaction_group_id" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearCreditGrantTransactionGroupID() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearCreditGrantTransactionGroupID()
	})
}

// SetCreditGrantedAt sets the "credit_granted_at" field.
func (u *ChargeCreditPurchaseUpsertBulk) SetCreditGrantedAt(v time.Time) *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.SetCreditGrantedAt(v)
	})
}

// UpdateCreditGrantedAt sets the "credit_granted_at" field to the value that was provided on create.
func (u *ChargeCreditPurchaseUpsertBulk) UpdateCreditGrantedAt() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.UpdateCreditGrantedAt()
	})
}

// ClearCreditGrantedAt clears the value of the "credit_granted_at" field.
func (u *ChargeCreditPurchaseUpsertBulk) ClearCreditGrantedAt() *ChargeCreditPurchaseUpsertBulk {
	return u.Update(func(s *ChargeCreditPurchaseUpsert) {
		s.ClearCreditGrantedAt()
	})
}

// Exec executes the query.
func (u *ChargeCreditPurchaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the ChargeCreditPurchaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ChargeCreditPurchaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChargeCreditPurchaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
