// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargeflatfeecostbasis"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ChargeFlatFeeCostBasisDelete is the builder for deleting a ChargeFlatFeeCostBasis entity.
type ChargeFlatFeeCostBasisDelete struct {
	config
	hooks    []Hook
	mutation *ChargeFlatFeeCostBasisMutation
}

// Where appends a list predicates to the ChargeFlatFeeCostBasisDelete builder.
func (_d *ChargeFlatFeeCostBasisDelete) Where(ps ...predicate.ChargeFlatFeeCostBasis) *ChargeFlatFeeCostBasisDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChargeFlatFeeCostBasisDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChargeFlatFeeCostBasisDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChargeFlatFeeCostBasisDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chargeflatfeecostbasis.Table, sqlgraph.NewFieldSpec(chargeflatfeecostbasis.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChargeFlatFeeCostBasisDeleteOne is the builder for deleting a single ChargeFlatFeeCostBasis entity.
type ChargeFlatFeeCostBasisDeleteOne struct {
	_d *ChargeFlatFeeCostBasisDelete
}

// Where appends a list predicates to the ChargeFlatFeeCostBasisDelete builder.
func (_d *ChargeFlatFeeCostBasisDeleteOne) Where(ps ...predicate.ChargeFlatFeeCostBasis) *ChargeFlatFeeCostBasisDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChargeFlatFeeCostBasisDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chargeflatfeecostbasis.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChargeFlatFeeCostBasisDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
