// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargeusagebasedcostbasis"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ChargeUsageBasedCostBasisDelete is the builder for deleting a ChargeUsageBasedCostBasis entity.
type ChargeUsageBasedCostBasisDelete struct {
	config
	hooks    []Hook
	mutation *ChargeUsageBasedCostBasisMutation
}

// Where appends a list predicates to the ChargeUsageBasedCostBasisDelete builder.
func (_d *ChargeUsageBasedCostBasisDelete) Where(ps ...predicate.ChargeUsageBasedCostBasis) *ChargeUsageBasedCostBasisDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChargeUsageBasedCostBasisDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChargeUsageBasedCostBasisDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChargeUsageBasedCostBasisDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chargeusagebasedcostbasis.Table, sqlgraph.NewFieldSpec(chargeusagebasedcostbasis.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChargeUsageBasedCostBasisDeleteOne is the builder for deleting a single ChargeUsageBasedCostBasis entity.
type ChargeUsageBasedCostBasisDeleteOne struct {
	_d *ChargeUsageBasedCostBasisDelete
}

// Where appends a list predicates to the ChargeUsageBasedCostBasisDelete builder.
func (_d *ChargeUsageBasedCostBasisDeleteOne) Where(ps ...predicate.ChargeUsageBasedCostBasis) *ChargeUsageBasedCostBasisDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChargeUsageBasedCostBasisDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chargeusagebasedcostbasis.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChargeUsageBasedCostBasisDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
