// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/alpacahq/alpacadecimal"
	"github.com/openmeterio/openmeter/openmeter/ent/db/billinginvoiceline"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargeflatfee"
	"github.com/openmeterio/openmeter/openmeter/ent/db/chargestandardinvoiceaccruedusage"
	"github.com/openmeterio/openmeter/pkg/models"
)

// ChargeStandardInvoiceAccruedUsage is the model entity for the ChargeStandardInvoiceAccruedUsage schema.
type ChargeStandardInvoiceAccruedUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Annotations holds the value of the "annotations" field.
	Annotations models.Annotations `json:"annotations,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount alpacadecimal.Decimal `json:"amount,omitempty"`
	// TaxesTotal holds the value of the "taxes_total" field.
	TaxesTotal alpacadecimal.Decimal `json:"taxes_total,omitempty"`
	// TaxesInclusiveTotal holds the value of the "taxes_inclusive_total" field.
	TaxesInclusiveTotal alpacadecimal.Decimal `json:"taxes_inclusive_total,omitempty"`
	// TaxesExclusiveTotal holds the value of the "taxes_exclusive_total" field.
	TaxesExclusiveTotal alpacadecimal.Decimal `json:"taxes_exclusive_total,omitempty"`
	// ChargesTotal holds the value of the "charges_total" field.
	ChargesTotal alpacadecimal.Decimal `json:"charges_total,omitempty"`
	// DiscountsTotal holds the value of the "discounts_total" field.
	DiscountsTotal alpacadecimal.Decimal `json:"discounts_total,omitempty"`
	// CreditsTotal holds the value of the "credits_total" field.
	CreditsTotal alpacadecimal.Decimal `json:"credits_total,omitempty"`
	// Total holds the value of the "total" field.
	Total alpacadecimal.Decimal `json:"total,omitempty"`
	// ChargeID holds the value of the "charge_id" field.
	ChargeID string `json:"charge_id,omitempty"`
	// LineID holds the value of the "line_id" field.
	LineID *string `json:"line_id,omitempty"`
	// ServicePeriodFrom holds the value of the "service_period_from" field.
	ServicePeriodFrom time.Time `json:"service_period_from,omitempty"`
	// ServicePeriodTo holds the value of the "service_period_to" field.
	ServicePeriodTo time.Time `json:"service_period_to,omitempty"`
	// Mutable holds the value of the "mutable" field.
	Mutable bool `json:"mutable,omitempty"`
	// LedgerTransactionGroupID holds the value of the "ledger_transaction_group_id" field.
	LedgerTransactionGroupID *string `json:"ledger_transaction_group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChargeStandardInvoiceAccruedUsageQuery when eager-loading is set.
	Edges        ChargeStandardInvoiceAccruedUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChargeStandardInvoiceAccruedUsageEdges holds the relations/edges for other nodes in the graph.
type ChargeStandardInvoiceAccruedUsageEdges struct {
	// BillingInvoiceLine holds the value of the billing_invoice_line edge.
	BillingInvoiceLine *BillingInvoiceLine `json:"billing_invoice_line,omitempty"`
	// FlatFee holds the value of the flat_fee edge.
	FlatFee *ChargeFlatFee `json:"flat_fee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BillingInvoiceLineOrErr returns the BillingInvoiceLine value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChargeStandardInvoiceAccruedUsageEdges) BillingInvoiceLineOrErr() (*BillingInvoiceLine, error) {
	if e.BillingInvoiceLine != nil {
		return e.BillingInvoiceLine, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: billinginvoiceline.Label}
	}
	return nil, &NotLoadedError{edge: "billing_invoice_line"}
}

// FlatFeeOrErr returns the FlatFee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChargeStandardInvoiceAccruedUsageEdges) FlatFeeOrErr() (*ChargeFlatFee, error) {
	if e.FlatFee != nil {
		return e.FlatFee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: chargeflatfee.Label}
	}
	return nil, &NotLoadedError{edge: "flat_fee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChargeStandardInvoiceAccruedUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chargestandardinvoiceaccruedusage.FieldAnnotations:
			values[i] = new([]byte)
		case chargestandardinvoiceaccruedusage.FieldAmount, chargestandardinvoiceaccruedusage.FieldTaxesTotal, chargestandardinvoiceaccruedusage.FieldTaxesInclusiveTotal, chargestandardinvoiceaccruedusage.FieldTaxesExclusiveTotal, chargestandardinvoiceaccruedusage.FieldChargesTotal, chargestandardinvoiceaccruedusage.FieldDiscountsTotal, chargestandardinvoiceaccruedusage.FieldCreditsTotal, chargestandardinvoiceaccruedusage.FieldTotal:
			values[i] = new(alpacadecimal.Decimal)
		case chargestandardinvoiceaccruedusage.FieldMutable:
			values[i] = new(sql.NullBool)
		case chargestandardinvoiceaccruedusage.FieldID, chargestandardinvoiceaccruedusage.FieldNamespace, chargestandardinvoiceaccruedusage.FieldChargeID, chargestandardinvoiceaccruedusage.FieldLineID, chargestandardinvoiceaccruedusage.FieldLedgerTransactionGroupID:
			values[i] = new(sql.NullString)
		case chargestandardinvoiceaccruedusage.FieldCreatedAt, chargestandardinvoiceaccruedusage.FieldUpdatedAt, chargestandardinvoiceaccruedusage.FieldDeletedAt, chargestandardinvoiceaccruedusage.FieldServicePeriodFrom, chargestandardinvoiceaccruedusage.FieldServicePeriodTo:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChargeStandardInvoiceAccruedUsage fields.
func (_m *ChargeStandardInvoiceAccruedUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chargestandardinvoiceaccruedusage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case chargestandardinvoiceaccruedusage.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case chargestandardinvoiceaccruedusage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chargestandardinvoiceaccruedusage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case chargestandardinvoiceaccruedusage.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case chargestandardinvoiceaccruedusage.FieldAnnotations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field annotations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Annotations); err != nil {
					return fmt.Errorf("unmarshal field annotations: %w", err)
				}
			}
		case chargestandardinvoiceaccruedusage.FieldAmount:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case chargestandardinvoiceaccruedusage.FieldTaxesTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field taxes_total", values[i])
			} else if value != nil {
				_m.TaxesTotal = *value
			}
		case chargestandardinvoiceaccruedusage.FieldTaxesInclusiveTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field taxes_inclusive_total", values[i])
			} else if value != nil {
				_m.TaxesInclusiveTotal = *value
			}
		case chargestandardinvoiceaccruedusage.FieldTaxesExclusiveTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field taxes_exclusive_total", values[i])
			} else if value != nil {
				_m.TaxesExclusiveTotal = *value
			}
		case chargestandardinvoiceaccruedusage.FieldChargesTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field charges_total", values[i])
			} else if value != nil {
				_m.ChargesTotal = *value
			}
		case chargestandardinvoiceaccruedusage.FieldDiscountsTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field discounts_total", values[i])
			} else if value != nil {
				_m.DiscountsTotal = *value
			}
		case chargestandardinvoiceaccruedusage.FieldCreditsTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field credits_total", values[i])
			} else if value != nil {
				_m.CreditsTotal = *value
			}
		case chargestandardinvoiceaccruedusage.FieldTotal:
			if value, ok := values[i].(*alpacadecimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value != nil {
				_m.Total = *value
			}
		case chargestandardinvoiceaccruedusage.FieldChargeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field charge_id", values[i])
			} else if value.Valid {
				_m.ChargeID = value.String
			}
		case chargestandardinvoiceaccruedusage.FieldLineID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field line_id", values[i])
			} else if value.Valid {
				_m.LineID = new(string)
				*_m.LineID = value.String
			}
		case chargestandardinvoiceaccruedusage.FieldServicePeriodFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field service_period_from", values[i])
			} else if value.Valid {
				_m.ServicePeriodFrom = value.Time
			}
		case chargestandardinvoiceaccruedusage.FieldServicePeriodTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field service_period_to", values[i])
			} else if value.Valid {
				_m.ServicePeriodTo = value.Time
			}
		case chargestandardinvoiceaccruedusage.FieldMutable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mutable", values[i])
			} else if value.Valid {
				_m.Mutable = value.Bool
			}
		case chargestandardinvoiceaccruedusage.FieldLedgerTransactionGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ledger_transaction_group_id", values[i])
			} else if value.Valid {
				_m.LedgerTransactionGroupID = new(string)
				*_m.LedgerTransactionGroupID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChargeStandardInvoiceAccruedUsage.
// This includes values selected through modifiers, order, etc.
func (_m *ChargeStandardInvoiceAccruedUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBillingInvoiceLine queries the "billing_invoice_line" edge of the ChargeStandardInvoiceAccruedUsage entity.
func (_m *ChargeStandardInvoiceAccruedUsage) QueryBillingInvoiceLine() *BillingInvoiceLineQuery {
	return NewChargeStandardInvoiceAccruedUsageClient(_m.config).QueryBillingInvoiceLine(_m)
}

// QueryFlatFee queries the "flat_fee" edge of the ChargeStandardInvoiceAccruedUsage entity.
func (_m *ChargeStandardInvoiceAccruedUsage) QueryFlatFee() *ChargeFlatFeeQuery {
	return NewChargeStandardInvoiceAccruedUsageClient(_m.config).QueryFlatFee(_m)
}

// Update returns a builder for updating this ChargeStandardInvoiceAccruedUsage.
// Note that you need to call ChargeStandardInvoiceAccruedUsage.Unwrap() before calling this method if this ChargeStandardInvoiceAccruedUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChargeStandardInvoiceAccruedUsage) Update() *ChargeStandardInvoiceAccruedUsageUpdateOne {
	return NewChargeStandardInvoiceAccruedUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChargeStandardInvoiceAccruedUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChargeStandardInvoiceAccruedUsage) Unwrap() *ChargeStandardInvoiceAccruedUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: ChargeStandardInvoiceAccruedUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChargeStandardInvoiceAccruedUsage) String() string {
	var builder strings.Builder
	builder.WriteString("ChargeStandardInvoiceAccruedUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("annotations=")
	builder.WriteString(fmt.Sprintf("%v", _m.Annotations))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("taxes_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxesTotal))
	builder.WriteString(", ")
	builder.WriteString("taxes_inclusive_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxesInclusiveTotal))
	builder.WriteString(", ")
	builder.WriteString("taxes_exclusive_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxesExclusiveTotal))
	builder.WriteString(", ")
	builder.WriteString("charges_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChargesTotal))
	builder.WriteString(", ")
	builder.WriteString("discounts_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountsTotal))
	builder.WriteString(", ")
	builder.WriteString("credits_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditsTotal))
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", _m.Total))
	builder.WriteString(", ")
	builder.WriteString("charge_id=")
	builder.WriteString(_m.ChargeID)
	builder.WriteString(", ")
	if v := _m.LineID; v != nil {
		builder.WriteString("line_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("service_period_from=")
	builder.WriteString(_m.ServicePeriodFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("service_period_to=")
	builder.WriteString(_m.ServicePeriodTo.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("mutable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mutable))
	builder.WriteString(", ")
	if v := _m.LedgerTransactionGroupID; v != nil {
		builder.WriteString("ledger_transaction_group_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ChargeStandardInvoiceAccruedUsages is a parsable slice of ChargeStandardInvoiceAccruedUsage.
type ChargeStandardInvoiceAccruedUsages []*ChargeStandardInvoiceAccruedUsage
