// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/ent/db/addon"
	"github.com/openmeterio/openmeter/openmeter/ent/db/addonratecard"
	"github.com/openmeterio/openmeter/openmeter/ent/db/currencycostbasis"
	"github.com/openmeterio/openmeter/openmeter/ent/db/customcurrency"
	"github.com/openmeterio/openmeter/openmeter/ent/db/plan"
	"github.com/openmeterio/openmeter/openmeter/ent/db/planratecard"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
	"github.com/openmeterio/openmeter/openmeter/ent/db/subscriptionitem"
)

// CustomCurrencyUpdate is the builder for updating CustomCurrency entities.
type CustomCurrencyUpdate struct {
	config
	hooks    []Hook
	mutation *CustomCurrencyMutation
}

// Where appends a list predicates to the CustomCurrencyUpdate builder.
func (_u *CustomCurrencyUpdate) Where(ps ...predicate.CustomCurrency) *CustomCurrencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomCurrencyUpdate) SetUpdatedAt(v time.Time) *CustomCurrencyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CustomCurrencyUpdate) SetDeletedAt(v time.Time) *CustomCurrencyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CustomCurrencyUpdate) SetNillableDeletedAt(v *time.Time) *CustomCurrencyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CustomCurrencyUpdate) ClearDeletedAt() *CustomCurrencyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CustomCurrencyUpdate) SetName(v string) *CustomCurrencyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomCurrencyUpdate) SetNillableName(v *string) *CustomCurrencyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *CustomCurrencyUpdate) SetSymbol(v string) *CustomCurrencyUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *CustomCurrencyUpdate) SetNillableSymbol(v *string) *CustomCurrencyUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// AddCostBasisHistoryIDs adds the "cost_basis_history" edge to the CurrencyCostBasis entity by IDs.
func (_u *CustomCurrencyUpdate) AddCostBasisHistoryIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.AddCostBasisHistoryIDs(ids...)
	return _u
}

// AddCostBasisHistory adds the "cost_basis_history" edges to the CurrencyCostBasis entity.
func (_u *CustomCurrencyUpdate) AddCostBasisHistory(v ...*CurrencyCostBasis) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCostBasisHistoryIDs(ids...)
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_u *CustomCurrencyUpdate) AddPlanIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.AddPlanIDs(ids...)
	return _u
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_u *CustomCurrencyUpdate) AddPlans(v ...*Plan) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanIDs(ids...)
}

// AddAddonIDs adds the "addons" edge to the Addon entity by IDs.
func (_u *CustomCurrencyUpdate) AddAddonIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.AddAddonIDs(ids...)
	return _u
}

// AddAddons adds the "addons" edges to the Addon entity.
func (_u *CustomCurrencyUpdate) AddAddons(v ...*Addon) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAddonIDs(ids...)
}

// AddPlanRateCardIDs adds the "plan_rate_cards" edge to the PlanRateCard entity by IDs.
func (_u *CustomCurrencyUpdate) AddPlanRateCardIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.AddPlanRateCardIDs(ids...)
	return _u
}

// AddPlanRateCards adds the "plan_rate_cards" edges to the PlanRateCard entity.
func (_u *CustomCurrencyUpdate) AddPlanRateCards(v ...*PlanRateCard) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanRateCardIDs(ids...)
}

// AddAddonRateCardIDs adds the "addon_rate_cards" edge to the AddonRateCard entity by IDs.
func (_u *CustomCurrencyUpdate) AddAddonRateCardIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.AddAddonRateCardIDs(ids...)
	return _u
}

// AddAddonRateCards adds the "addon_rate_cards" edges to the AddonRateCard entity.
func (_u *CustomCurrencyUpdate) AddAddonRateCards(v ...*AddonRateCard) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAddonRateCardIDs(ids...)
}

// AddSubscriptionItemIDs adds the "subscription_items" edge to the SubscriptionItem entity by IDs.
func (_u *CustomCurrencyUpdate) AddSubscriptionItemIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.AddSubscriptionItemIDs(ids...)
	return _u
}

// AddSubscriptionItems adds the "subscription_items" edges to the SubscriptionItem entity.
func (_u *CustomCurrencyUpdate) AddSubscriptionItems(v ...*SubscriptionItem) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionItemIDs(ids...)
}

// Mutation returns the CustomCurrencyMutation object of the builder.
func (_u *CustomCurrencyUpdate) Mutation() *CustomCurrencyMutation {
	return _u.mutation
}

// ClearCostBasisHistory clears all "cost_basis_history" edges to the CurrencyCostBasis entity.
func (_u *CustomCurrencyUpdate) ClearCostBasisHistory() *CustomCurrencyUpdate {
	_u.mutation.ClearCostBasisHistory()
	return _u
}

// RemoveCostBasisHistoryIDs removes the "cost_basis_history" edge to CurrencyCostBasis entities by IDs.
func (_u *CustomCurrencyUpdate) RemoveCostBasisHistoryIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.RemoveCostBasisHistoryIDs(ids...)
	return _u
}

// RemoveCostBasisHistory removes "cost_basis_history" edges to CurrencyCostBasis entities.
func (_u *CustomCurrencyUpdate) RemoveCostBasisHistory(v ...*CurrencyCostBasis) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCostBasisHistoryIDs(ids...)
}

// ClearPlans clears all "plans" edges to the Plan entity.
func (_u *CustomCurrencyUpdate) ClearPlans() *CustomCurrencyUpdate {
	_u.mutation.ClearPlans()
	return _u
}

// RemovePlanIDs removes the "plans" edge to Plan entities by IDs.
func (_u *CustomCurrencyUpdate) RemovePlanIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.RemovePlanIDs(ids...)
	return _u
}

// RemovePlans removes "plans" edges to Plan entities.
func (_u *CustomCurrencyUpdate) RemovePlans(v ...*Plan) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanIDs(ids...)
}

// ClearAddons clears all "addons" edges to the Addon entity.
func (_u *CustomCurrencyUpdate) ClearAddons() *CustomCurrencyUpdate {
	_u.mutation.ClearAddons()
	return _u
}

// RemoveAddonIDs removes the "addons" edge to Addon entities by IDs.
func (_u *CustomCurrencyUpdate) RemoveAddonIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.RemoveAddonIDs(ids...)
	return _u
}

// RemoveAddons removes "addons" edges to Addon entities.
func (_u *CustomCurrencyUpdate) RemoveAddons(v ...*Addon) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAddonIDs(ids...)
}

// ClearPlanRateCards clears all "plan_rate_cards" edges to the PlanRateCard entity.
func (_u *CustomCurrencyUpdate) ClearPlanRateCards() *CustomCurrencyUpdate {
	_u.mutation.ClearPlanRateCards()
	return _u
}

// RemovePlanRateCardIDs removes the "plan_rate_cards" edge to PlanRateCard entities by IDs.
func (_u *CustomCurrencyUpdate) RemovePlanRateCardIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.RemovePlanRateCardIDs(ids...)
	return _u
}

// RemovePlanRateCards removes "plan_rate_cards" edges to PlanRateCard entities.
func (_u *CustomCurrencyUpdate) RemovePlanRateCards(v ...*PlanRateCard) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanRateCardIDs(ids...)
}

// ClearAddonRateCards clears all "addon_rate_cards" edges to the AddonRateCard entity.
func (_u *CustomCurrencyUpdate) ClearAddonRateCards() *CustomCurrencyUpdate {
	_u.mutation.ClearAddonRateCards()
	return _u
}

// RemoveAddonRateCardIDs removes the "addon_rate_cards" edge to AddonRateCard entities by IDs.
func (_u *CustomCurrencyUpdate) RemoveAddonRateCardIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.RemoveAddonRateCardIDs(ids...)
	return _u
}

// RemoveAddonRateCards removes "addon_rate_cards" edges to AddonRateCard entities.
func (_u *CustomCurrencyUpdate) RemoveAddonRateCards(v ...*AddonRateCard) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAddonRateCardIDs(ids...)
}

// ClearSubscriptionItems clears all "subscription_items" edges to the SubscriptionItem entity.
func (_u *CustomCurrencyUpdate) ClearSubscriptionItems() *CustomCurrencyUpdate {
	_u.mutation.ClearSubscriptionItems()
	return _u
}

// RemoveSubscriptionItemIDs removes the "subscription_items" edge to SubscriptionItem entities by IDs.
func (_u *CustomCurrencyUpdate) RemoveSubscriptionItemIDs(ids ...string) *CustomCurrencyUpdate {
	_u.mutation.RemoveSubscriptionItemIDs(ids...)
	return _u
}

// RemoveSubscriptionItems removes "subscription_items" edges to SubscriptionItem entities.
func (_u *CustomCurrencyUpdate) RemoveSubscriptionItems(v ...*SubscriptionItem) *CustomCurrencyUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomCurrencyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomCurrencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomCurrencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomCurrencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomCurrencyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customcurrency.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomCurrencyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := customcurrency.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "CustomCurrency.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := customcurrency.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`db: validator failed for field "CustomCurrency.symbol": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomCurrencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customcurrency.Table, customcurrency.Columns, sqlgraph.NewFieldSpec(customcurrency.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customcurrency.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(customcurrency.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(customcurrency.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(customcurrency.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(customcurrency.FieldSymbol, field.TypeString, value)
	}
	if _u.mutation.CostBasisHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.CostBasisHistoryTable,
			Columns: []string{customcurrency.CostBasisHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currencycostbasis.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCostBasisHistoryIDs(); len(nodes) > 0 && !_u.mutation.CostBasisHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.CostBasisHistoryTable,
			Columns: []string{customcurrency.CostBasisHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currencycostbasis.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CostBasisHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.CostBasisHistoryTable,
			Columns: []string{customcurrency.CostBasisHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currencycostbasis.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlansTable,
			Columns: []string{customcurrency.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlansIDs(); len(nodes) > 0 && !_u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlansTable,
			Columns: []string{customcurrency.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlansTable,
			Columns: []string{customcurrency.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AddonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonsTable,
			Columns: []string{customcurrency.AddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAddonsIDs(); len(nodes) > 0 && !_u.mutation.AddonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonsTable,
			Columns: []string{customcurrency.AddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonsTable,
			Columns: []string{customcurrency.AddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlanRateCardsTable,
			Columns: []string{customcurrency.PlanRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(planratecard.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlanRateCardsIDs(); len(nodes) > 0 && !_u.mutation.PlanRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlanRateCardsTable,
			Columns: []string{customcurrency.PlanRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(planratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanRateCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlanRateCardsTable,
			Columns: []string{customcurrency.PlanRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(planratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AddonRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonRateCardsTable,
			Columns: []string{customcurrency.AddonRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addonratecard.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAddonRateCardsIDs(); len(nodes) > 0 && !_u.mutation.AddonRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonRateCardsTable,
			Columns: []string{customcurrency.AddonRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addonratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddonRateCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonRateCardsTable,
			Columns: []string{customcurrency.AddonRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addonratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.SubscriptionItemsTable,
			Columns: []string{customcurrency.SubscriptionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionItemsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.SubscriptionItemsTable,
			Columns: []string{customcurrency.SubscriptionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.SubscriptionItemsTable,
			Columns: []string{customcurrency.SubscriptionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomCurrencyUpdateOne is the builder for updating a single CustomCurrency entity.
type CustomCurrencyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomCurrencyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomCurrencyUpdateOne) SetUpdatedAt(v time.Time) *CustomCurrencyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CustomCurrencyUpdateOne) SetDeletedAt(v time.Time) *CustomCurrencyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CustomCurrencyUpdateOne) SetNillableDeletedAt(v *time.Time) *CustomCurrencyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CustomCurrencyUpdateOne) ClearDeletedAt() *CustomCurrencyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CustomCurrencyUpdateOne) SetName(v string) *CustomCurrencyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomCurrencyUpdateOne) SetNillableName(v *string) *CustomCurrencyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *CustomCurrencyUpdateOne) SetSymbol(v string) *CustomCurrencyUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *CustomCurrencyUpdateOne) SetNillableSymbol(v *string) *CustomCurrencyUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// AddCostBasisHistoryIDs adds the "cost_basis_history" edge to the CurrencyCostBasis entity by IDs.
func (_u *CustomCurrencyUpdateOne) AddCostBasisHistoryIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.AddCostBasisHistoryIDs(ids...)
	return _u
}

// AddCostBasisHistory adds the "cost_basis_history" edges to the CurrencyCostBasis entity.
func (_u *CustomCurrencyUpdateOne) AddCostBasisHistory(v ...*CurrencyCostBasis) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCostBasisHistoryIDs(ids...)
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (_u *CustomCurrencyUpdateOne) AddPlanIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.AddPlanIDs(ids...)
	return _u
}

// AddPlans adds the "plans" edges to the Plan entity.
func (_u *CustomCurrencyUpdateOne) AddPlans(v ...*Plan) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanIDs(ids...)
}

// AddAddonIDs adds the "addons" edge to the Addon entity by IDs.
func (_u *CustomCurrencyUpdateOne) AddAddonIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.AddAddonIDs(ids...)
	return _u
}

// AddAddons adds the "addons" edges to the Addon entity.
func (_u *CustomCurrencyUpdateOne) AddAddons(v ...*Addon) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAddonIDs(ids...)
}

// AddPlanRateCardIDs adds the "plan_rate_cards" edge to the PlanRateCard entity by IDs.
func (_u *CustomCurrencyUpdateOne) AddPlanRateCardIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.AddPlanRateCardIDs(ids...)
	return _u
}

// AddPlanRateCards adds the "plan_rate_cards" edges to the PlanRateCard entity.
func (_u *CustomCurrencyUpdateOne) AddPlanRateCards(v ...*PlanRateCard) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlanRateCardIDs(ids...)
}

// AddAddonRateCardIDs adds the "addon_rate_cards" edge to the AddonRateCard entity by IDs.
func (_u *CustomCurrencyUpdateOne) AddAddonRateCardIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.AddAddonRateCardIDs(ids...)
	return _u
}

// AddAddonRateCards adds the "addon_rate_cards" edges to the AddonRateCard entity.
func (_u *CustomCurrencyUpdateOne) AddAddonRateCards(v ...*AddonRateCard) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAddonRateCardIDs(ids...)
}

// AddSubscriptionItemIDs adds the "subscription_items" edge to the SubscriptionItem entity by IDs.
func (_u *CustomCurrencyUpdateOne) AddSubscriptionItemIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.AddSubscriptionItemIDs(ids...)
	return _u
}

// AddSubscriptionItems adds the "subscription_items" edges to the SubscriptionItem entity.
func (_u *CustomCurrencyUpdateOne) AddSubscriptionItems(v ...*SubscriptionItem) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionItemIDs(ids...)
}

// Mutation returns the CustomCurrencyMutation object of the builder.
func (_u *CustomCurrencyUpdateOne) Mutation() *CustomCurrencyMutation {
	return _u.mutation
}

// ClearCostBasisHistory clears all "cost_basis_history" edges to the CurrencyCostBasis entity.
func (_u *CustomCurrencyUpdateOne) ClearCostBasisHistory() *CustomCurrencyUpdateOne {
	_u.mutation.ClearCostBasisHistory()
	return _u
}

// RemoveCostBasisHistoryIDs removes the "cost_basis_history" edge to CurrencyCostBasis entities by IDs.
func (_u *CustomCurrencyUpdateOne) RemoveCostBasisHistoryIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.RemoveCostBasisHistoryIDs(ids...)
	return _u
}

// RemoveCostBasisHistory removes "cost_basis_history" edges to CurrencyCostBasis entities.
func (_u *CustomCurrencyUpdateOne) RemoveCostBasisHistory(v ...*CurrencyCostBasis) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCostBasisHistoryIDs(ids...)
}

// ClearPlans clears all "plans" edges to the Plan entity.
func (_u *CustomCurrencyUpdateOne) ClearPlans() *CustomCurrencyUpdateOne {
	_u.mutation.ClearPlans()
	return _u
}

// RemovePlanIDs removes the "plans" edge to Plan entities by IDs.
func (_u *CustomCurrencyUpdateOne) RemovePlanIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.RemovePlanIDs(ids...)
	return _u
}

// RemovePlans removes "plans" edges to Plan entities.
func (_u *CustomCurrencyUpdateOne) RemovePlans(v ...*Plan) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanIDs(ids...)
}

// ClearAddons clears all "addons" edges to the Addon entity.
func (_u *CustomCurrencyUpdateOne) ClearAddons() *CustomCurrencyUpdateOne {
	_u.mutation.ClearAddons()
	return _u
}

// RemoveAddonIDs removes the "addons" edge to Addon entities by IDs.
func (_u *CustomCurrencyUpdateOne) RemoveAddonIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.RemoveAddonIDs(ids...)
	return _u
}

// RemoveAddons removes "addons" edges to Addon entities.
func (_u *CustomCurrencyUpdateOne) RemoveAddons(v ...*Addon) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAddonIDs(ids...)
}

// ClearPlanRateCards clears all "plan_rate_cards" edges to the PlanRateCard entity.
func (_u *CustomCurrencyUpdateOne) ClearPlanRateCards() *CustomCurrencyUpdateOne {
	_u.mutation.ClearPlanRateCards()
	return _u
}

// RemovePlanRateCardIDs removes the "plan_rate_cards" edge to PlanRateCard entities by IDs.
func (_u *CustomCurrencyUpdateOne) RemovePlanRateCardIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.RemovePlanRateCardIDs(ids...)
	return _u
}

// RemovePlanRateCards removes "plan_rate_cards" edges to PlanRateCard entities.
func (_u *CustomCurrencyUpdateOne) RemovePlanRateCards(v ...*PlanRateCard) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlanRateCardIDs(ids...)
}

// ClearAddonRateCards clears all "addon_rate_cards" edges to the AddonRateCard entity.
func (_u *CustomCurrencyUpdateOne) ClearAddonRateCards() *CustomCurrencyUpdateOne {
	_u.mutation.ClearAddonRateCards()
	return _u
}

// RemoveAddonRateCardIDs removes the "addon_rate_cards" edge to AddonRateCard entities by IDs.
func (_u *CustomCurrencyUpdateOne) RemoveAddonRateCardIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.RemoveAddonRateCardIDs(ids...)
	return _u
}

// RemoveAddonRateCards removes "addon_rate_cards" edges to AddonRateCard entities.
func (_u *CustomCurrencyUpdateOne) RemoveAddonRateCards(v ...*AddonRateCard) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAddonRateCardIDs(ids...)
}

// ClearSubscriptionItems clears all "subscription_items" edges to the SubscriptionItem entity.
func (_u *CustomCurrencyUpdateOne) ClearSubscriptionItems() *CustomCurrencyUpdateOne {
	_u.mutation.ClearSubscriptionItems()
	return _u
}

// RemoveSubscriptionItemIDs removes the "subscription_items" edge to SubscriptionItem entities by IDs.
func (_u *CustomCurrencyUpdateOne) RemoveSubscriptionItemIDs(ids ...string) *CustomCurrencyUpdateOne {
	_u.mutation.RemoveSubscriptionItemIDs(ids...)
	return _u
}

// RemoveSubscriptionItems removes "subscription_items" edges to SubscriptionItem entities.
func (_u *CustomCurrencyUpdateOne) RemoveSubscriptionItems(v ...*SubscriptionItem) *CustomCurrencyUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionItemIDs(ids...)
}

// Where appends a list predicates to the CustomCurrencyUpdate builder.
func (_u *CustomCurrencyUpdateOne) Where(ps ...predicate.CustomCurrency) *CustomCurrencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomCurrencyUpdateOne) Select(field string, fields ...string) *CustomCurrencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomCurrency entity.
func (_u *CustomCurrencyUpdateOne) Save(ctx context.Context) (*CustomCurrency, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomCurrencyUpdateOne) SaveX(ctx context.Context) *CustomCurrency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomCurrencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomCurrencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomCurrencyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customcurrency.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomCurrencyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := customcurrency.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "CustomCurrency.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := customcurrency.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`db: validator failed for field "CustomCurrency.symbol": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomCurrencyUpdateOne) sqlSave(ctx context.Context) (_node *CustomCurrency, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customcurrency.Table, customcurrency.Columns, sqlgraph.NewFieldSpec(customcurrency.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "CustomCurrency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customcurrency.FieldID)
		for _, f := range fields {
			if !customcurrency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != customcurrency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customcurrency.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(customcurrency.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(customcurrency.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(customcurrency.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(customcurrency.FieldSymbol, field.TypeString, value)
	}
	if _u.mutation.CostBasisHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.CostBasisHistoryTable,
			Columns: []string{customcurrency.CostBasisHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currencycostbasis.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCostBasisHistoryIDs(); len(nodes) > 0 && !_u.mutation.CostBasisHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.CostBasisHistoryTable,
			Columns: []string{customcurrency.CostBasisHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currencycostbasis.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CostBasisHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.CostBasisHistoryTable,
			Columns: []string{customcurrency.CostBasisHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(currencycostbasis.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlansTable,
			Columns: []string{customcurrency.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlansIDs(); len(nodes) > 0 && !_u.mutation.PlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlansTable,
			Columns: []string{customcurrency.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlansTable,
			Columns: []string{customcurrency.PlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AddonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonsTable,
			Columns: []string{customcurrency.AddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAddonsIDs(); len(nodes) > 0 && !_u.mutation.AddonsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonsTable,
			Columns: []string{customcurrency.AddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonsTable,
			Columns: []string{customcurrency.AddonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addon.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlanRateCardsTable,
			Columns: []string{customcurrency.PlanRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(planratecard.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlanRateCardsIDs(); len(nodes) > 0 && !_u.mutation.PlanRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlanRateCardsTable,
			Columns: []string{customcurrency.PlanRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(planratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanRateCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.PlanRateCardsTable,
			Columns: []string{customcurrency.PlanRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(planratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AddonRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonRateCardsTable,
			Columns: []string{customcurrency.AddonRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addonratecard.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAddonRateCardsIDs(); len(nodes) > 0 && !_u.mutation.AddonRateCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonRateCardsTable,
			Columns: []string{customcurrency.AddonRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addonratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AddonRateCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.AddonRateCardsTable,
			Columns: []string{customcurrency.AddonRateCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(addonratecard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.SubscriptionItemsTable,
			Columns: []string{customcurrency.SubscriptionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionItemsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.SubscriptionItemsTable,
			Columns: []string{customcurrency.SubscriptionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customcurrency.SubscriptionItemsTable,
			Columns: []string{customcurrency.SubscriptionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CustomCurrency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customcurrency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
