// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmeterio/openmeter/openmeter/ent/db/ledgerdimension"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
	"github.com/openmeterio/openmeter/pkg/models"
)

// LedgerDimensionUpdate is the builder for updating LedgerDimension entities.
type LedgerDimensionUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerDimensionMutation
}

// Where appends a list predicates to the LedgerDimensionUpdate builder.
func (_u *LedgerDimensionUpdate) Where(ps ...predicate.LedgerDimension) *LedgerDimensionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnotations sets the "annotations" field.
func (_u *LedgerDimensionUpdate) SetAnnotations(v models.Annotations) *LedgerDimensionUpdate {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *LedgerDimensionUpdate) ClearAnnotations() *LedgerDimensionUpdate {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LedgerDimensionUpdate) SetUpdatedAt(v time.Time) *LedgerDimensionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LedgerDimensionUpdate) SetDeletedAt(v time.Time) *LedgerDimensionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LedgerDimensionUpdate) SetNillableDeletedAt(v *time.Time) *LedgerDimensionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LedgerDimensionUpdate) ClearDeletedAt() *LedgerDimensionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the LedgerDimensionMutation object of the builder.
func (_u *LedgerDimensionUpdate) Mutation() *LedgerDimensionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerDimensionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerDimensionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerDimensionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerDimensionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LedgerDimensionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ledgerdimension.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LedgerDimensionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ledgerdimension.Table, ledgerdimension.Columns, sqlgraph.NewFieldSpec(ledgerdimension.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(ledgerdimension.FieldAnnotations, field.TypeJSON, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(ledgerdimension.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ledgerdimension.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ledgerdimension.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ledgerdimension.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgerdimension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerDimensionUpdateOne is the builder for updating a single LedgerDimension entity.
type LedgerDimensionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerDimensionMutation
}

// SetAnnotations sets the "annotations" field.
func (_u *LedgerDimensionUpdateOne) SetAnnotations(v models.Annotations) *LedgerDimensionUpdateOne {
	_u.mutation.SetAnnotations(v)
	return _u
}

// ClearAnnotations clears the value of the "annotations" field.
func (_u *LedgerDimensionUpdateOne) ClearAnnotations() *LedgerDimensionUpdateOne {
	_u.mutation.ClearAnnotations()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LedgerDimensionUpdateOne) SetUpdatedAt(v time.Time) *LedgerDimensionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LedgerDimensionUpdateOne) SetDeletedAt(v time.Time) *LedgerDimensionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LedgerDimensionUpdateOne) SetNillableDeletedAt(v *time.Time) *LedgerDimensionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LedgerDimensionUpdateOne) ClearDeletedAt() *LedgerDimensionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the LedgerDimensionMutation object of the builder.
func (_u *LedgerDimensionUpdateOne) Mutation() *LedgerDimensionMutation {
	return _u.mutation
}

// Where appends a list predicates to the LedgerDimensionUpdate builder.
func (_u *LedgerDimensionUpdateOne) Where(ps ...predicate.LedgerDimension) *LedgerDimensionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerDimensionUpdateOne) Select(field string, fields ...string) *LedgerDimensionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LedgerDimension entity.
func (_u *LedgerDimensionUpdateOne) Save(ctx context.Context) (*LedgerDimension, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerDimensionUpdateOne) SaveX(ctx context.Context) *LedgerDimension {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerDimensionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerDimensionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LedgerDimensionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ledgerdimension.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LedgerDimensionUpdateOne) sqlSave(ctx context.Context) (_node *LedgerDimension, err error) {
	_spec := sqlgraph.NewUpdateSpec(ledgerdimension.Table, ledgerdimension.Columns, sqlgraph.NewFieldSpec(ledgerdimension.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "LedgerDimension.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgerdimension.FieldID)
		for _, f := range fields {
			if !ledgerdimension.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != ledgerdimension.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Annotations(); ok {
		_spec.SetField(ledgerdimension.FieldAnnotations, field.TypeJSON, value)
	}
	if _u.mutation.AnnotationsCleared() {
		_spec.ClearField(ledgerdimension.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ledgerdimension.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ledgerdimension.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ledgerdimension.FieldDeletedAt, field.TypeTime)
	}
	_node = &LedgerDimension{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgerdimension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
