// Code generated by @openmeter/typespec-go. DO NOT EDIT.

package openmeter

import (
	"context"
	"fmt"
	"iter"
	"net/http"
	"net/url"
)

type InvoicesService struct {
	client *Client
}

type InvoiceFilter struct {
	// Filter by invoice status.
	Status *StringExactFilter
	// Filter by customer ID.
	CustomerID *StringExactFilter
	// Filter by the time the invoice was issued.
	IssuedAt *DateTimeFilter
	// Filter by service period start.
	ServicePeriodStart *DateTimeFilter
	// Filter by invoice creation time.
	CreatedAt *DateTimeFilter
}

type InvoiceListParams struct {
	Page   *PageParams
	Sort   *Sort
	Filter *InvoiceFilter
}

func (p InvoiceListParams) values() url.Values {
	q := url.Values{}

	addPageParams(q, p.Page)

	addSort(q, "sort", p.Sort)

	if p.Filter != nil {
		addStringExactFilter(q, "filter[status]", p.Filter.Status)
		addStringExactFilter(q, "filter[customer_id]", p.Filter.CustomerID)
		addDateTimeFilter(q, "filter[issued_at]", p.Filter.IssuedAt)
		addDateTimeFilter(q, "filter[service_period_start]", p.Filter.ServicePeriodStart)
		addDateTimeFilter(q, "filter[created_at]", p.Filter.CreatedAt)
	}

	return q
}

// List billing invoices.
//
// Returns a page of invoices. Gathering invoices are never included. Use `filter`
// to narrow by status, customer, dates, or service period start. Use `sort` to
// control ordering.
func (s *InvoicesService) List(ctx context.Context, params InvoiceListParams) (*InvoicePagePaginatedResponse, error) {
	path := "/openmeter/billing/invoices"

	req, err := s.client.newRequestWithContentType(ctx, http.MethodGet, path, params.values(), nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out InvoicePagePaginatedResponse
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// ListAll returns an iterator over all Invoice results, fetching pages of List transparently. Iteration stops at the first error, which is yielded as the second value.
func (s *InvoicesService) ListAll(ctx context.Context, params InvoiceListParams) iter.Seq2[Invoice, error] {
	return paginate(params.Page, func(page, size int) ([]Invoice, int, error) {
		pageParams := params
		pageParams.Page = &PageParams{Size: Int(size), Number: Int(page)}

		resp, err := s.List(ctx, pageParams)
		if err != nil {
			return nil, 0, err
		}

		return resp.Data, resp.Meta.Page.Total, nil
	})
}

// Get a billing invoice by ID.
//
// Returns the full invoice resource including line items, status details, totals,
// and workflow configuration snapshot.
func (s *InvoicesService) Get(ctx context.Context, invoiceID string) (*Invoice, error) {
	if invoiceID == "" {
		return nil, fmt.Errorf("openmeter: %s must not be empty: %w", "invoiceID", ErrEmptyID)
	}

	path := "/openmeter/billing/invoices/{invoiceId}"

	path = replacePathParam(path, "invoiceId", invoiceID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodGet, path, nil, nil, "", "application/json")
	if err != nil {
		return nil, err
	}

	var out Invoice
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// Update a billing invoice.
//
// Only the mutable fields of the invoice can be edited: description, labels,
// supplier, customer, workflow settings, and top-level lines. Top-level lines are
// matched by `id`; lines without an `id` are created, and existing lines omitted
// from `lines` are deleted. Detailed (child) lines are always computed and cannot
// be edited directly. Only invoices in draft status can be updated.
func (s *InvoicesService) Update(ctx context.Context, invoiceID string, request UpdateInvoiceRequest) (*Invoice, error) {
	if invoiceID == "" {
		return nil, fmt.Errorf("openmeter: %s must not be empty: %w", "invoiceID", ErrEmptyID)
	}

	path := "/openmeter/billing/invoices/{invoiceId}"

	path = replacePathParam(path, "invoiceId", invoiceID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodPut, path, nil, request, "application/json", "application/json")
	if err != nil {
		return nil, err
	}

	var out Invoice
	if err := s.client.doJSON(req, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// Delete a billing invoice.
//
// Only standard invoices in draft status can be deleted. Deleting an invoice will
// also delete all associated line items and workflow configuration.
func (s *InvoicesService) Delete(ctx context.Context, invoiceID string) error {
	if invoiceID == "" {
		return fmt.Errorf("openmeter: %s must not be empty: %w", "invoiceID", ErrEmptyID)
	}

	path := "/openmeter/billing/invoices/{invoiceId}"

	path = replacePathParam(path, "invoiceId", invoiceID)

	req, err := s.client.newRequestWithContentType(ctx, http.MethodDelete, path, nil, nil, "", "")
	if err != nil {
		return err
	}

	_, err = s.client.doRaw(req)
	return err
}
