// Code generated by ent, DO NOT EDIT.

package currencycostbasis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/alpacahq/alpacadecimal"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
	"github.com/openmeterio/openmeter/pkg/currencyx"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldDeletedAt, v))
}

// CurrencyID applies equality check predicate on the "currency_id" field. It's identical to CurrencyIDEQ.
func CurrencyID(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldCurrencyID, v))
}

// FiatCode applies equality check predicate on the "fiat_code" field. It's identical to FiatCodeEQ.
func FiatCode(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldFiatCode, vc))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldRate, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveTo applies equality check predicate on the "effective_to" field. It's identical to EffectiveToEQ.
func EffectiveTo(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldEffectiveTo, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotNull(FieldDeletedAt))
}

// CurrencyIDEQ applies the EQ predicate on the "currency_id" field.
func CurrencyIDEQ(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldCurrencyID, v))
}

// CurrencyIDNEQ applies the NEQ predicate on the "currency_id" field.
func CurrencyIDNEQ(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldCurrencyID, v))
}

// CurrencyIDIn applies the In predicate on the "currency_id" field.
func CurrencyIDIn(vs ...string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldCurrencyID, vs...))
}

// CurrencyIDNotIn applies the NotIn predicate on the "currency_id" field.
func CurrencyIDNotIn(vs ...string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldCurrencyID, vs...))
}

// CurrencyIDGT applies the GT predicate on the "currency_id" field.
func CurrencyIDGT(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldCurrencyID, v))
}

// CurrencyIDGTE applies the GTE predicate on the "currency_id" field.
func CurrencyIDGTE(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldCurrencyID, v))
}

// CurrencyIDLT applies the LT predicate on the "currency_id" field.
func CurrencyIDLT(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldCurrencyID, v))
}

// CurrencyIDLTE applies the LTE predicate on the "currency_id" field.
func CurrencyIDLTE(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldCurrencyID, v))
}

// CurrencyIDContains applies the Contains predicate on the "currency_id" field.
func CurrencyIDContains(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldContains(FieldCurrencyID, v))
}

// CurrencyIDHasPrefix applies the HasPrefix predicate on the "currency_id" field.
func CurrencyIDHasPrefix(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldHasPrefix(FieldCurrencyID, v))
}

// CurrencyIDHasSuffix applies the HasSuffix predicate on the "currency_id" field.
func CurrencyIDHasSuffix(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldHasSuffix(FieldCurrencyID, v))
}

// CurrencyIDEqualFold applies the EqualFold predicate on the "currency_id" field.
func CurrencyIDEqualFold(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEqualFold(FieldCurrencyID, v))
}

// CurrencyIDContainsFold applies the ContainsFold predicate on the "currency_id" field.
func CurrencyIDContainsFold(v string) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldContainsFold(FieldCurrencyID, v))
}

// FiatCodeEQ applies the EQ predicate on the "fiat_code" field.
func FiatCodeEQ(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldFiatCode, vc))
}

// FiatCodeNEQ applies the NEQ predicate on the "fiat_code" field.
func FiatCodeNEQ(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldFiatCode, vc))
}

// FiatCodeIn applies the In predicate on the "fiat_code" field.
func FiatCodeIn(vs ...currencyx.Code) predicate.CurrencyCostBasis {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldFiatCode, v...))
}

// FiatCodeNotIn applies the NotIn predicate on the "fiat_code" field.
func FiatCodeNotIn(vs ...currencyx.Code) predicate.CurrencyCostBasis {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldFiatCode, v...))
}

// FiatCodeGT applies the GT predicate on the "fiat_code" field.
func FiatCodeGT(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldFiatCode, vc))
}

// FiatCodeGTE applies the GTE predicate on the "fiat_code" field.
func FiatCodeGTE(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldFiatCode, vc))
}

// FiatCodeLT applies the LT predicate on the "fiat_code" field.
func FiatCodeLT(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldFiatCode, vc))
}

// FiatCodeLTE applies the LTE predicate on the "fiat_code" field.
func FiatCodeLTE(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldFiatCode, vc))
}

// FiatCodeContains applies the Contains predicate on the "fiat_code" field.
func FiatCodeContains(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldContains(FieldFiatCode, vc))
}

// FiatCodeHasPrefix applies the HasPrefix predicate on the "fiat_code" field.
func FiatCodeHasPrefix(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldHasPrefix(FieldFiatCode, vc))
}

// FiatCodeHasSuffix applies the HasSuffix predicate on the "fiat_code" field.
func FiatCodeHasSuffix(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldHasSuffix(FieldFiatCode, vc))
}

// FiatCodeEqualFold applies the EqualFold predicate on the "fiat_code" field.
func FiatCodeEqualFold(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldEqualFold(FieldFiatCode, vc))
}

// FiatCodeContainsFold applies the ContainsFold predicate on the "fiat_code" field.
func FiatCodeContainsFold(v currencyx.Code) predicate.CurrencyCostBasis {
	vc := string(v)
	return predicate.CurrencyCostBasis(sql.FieldContainsFold(FieldFiatCode, vc))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v alpacadecimal.Decimal) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldRate, v))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveToEQ applies the EQ predicate on the "effective_to" field.
func EffectiveToEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldEQ(FieldEffectiveTo, v))
}

// EffectiveToNEQ applies the NEQ predicate on the "effective_to" field.
func EffectiveToNEQ(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNEQ(FieldEffectiveTo, v))
}

// EffectiveToIn applies the In predicate on the "effective_to" field.
func EffectiveToIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIn(FieldEffectiveTo, vs...))
}

// EffectiveToNotIn applies the NotIn predicate on the "effective_to" field.
func EffectiveToNotIn(vs ...time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotIn(FieldEffectiveTo, vs...))
}

// EffectiveToGT applies the GT predicate on the "effective_to" field.
func EffectiveToGT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGT(FieldEffectiveTo, v))
}

// EffectiveToGTE applies the GTE predicate on the "effective_to" field.
func EffectiveToGTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldGTE(FieldEffectiveTo, v))
}

// EffectiveToLT applies the LT predicate on the "effective_to" field.
func EffectiveToLT(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLT(FieldEffectiveTo, v))
}

// EffectiveToLTE applies the LTE predicate on the "effective_to" field.
func EffectiveToLTE(v time.Time) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldLTE(FieldEffectiveTo, v))
}

// EffectiveToIsNil applies the IsNil predicate on the "effective_to" field.
func EffectiveToIsNil() predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldIsNull(FieldEffectiveTo))
}

// EffectiveToNotNil applies the NotNil predicate on the "effective_to" field.
func EffectiveToNotNil() predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.FieldNotNull(FieldEffectiveTo))
}

// HasCurrency applies the HasEdge predicate on the "currency" edge.
func HasCurrency() predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CurrencyTable, CurrencyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrencyWith applies the HasEdge predicate on the "currency" edge with a given conditions (other predicates).
func HasCurrencyWith(preds ...predicate.CustomCurrency) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(func(s *sql.Selector) {
		step := newCurrencyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptionPins applies the HasEdge predicate on the "subscription_pins" edge.
func HasSubscriptionPins() predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionPinsTable, SubscriptionPinsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionPinsWith applies the HasEdge predicate on the "subscription_pins" edge with a given conditions (other predicates).
func HasSubscriptionPinsWith(preds ...predicate.SubscriptionCostBasisPin) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(func(s *sql.Selector) {
		step := newSubscriptionPinsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CurrencyCostBasis) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CurrencyCostBasis) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CurrencyCostBasis) predicate.CurrencyCostBasis {
	return predicate.CurrencyCostBasis(sql.NotPredicates(p))
}
