blockExoticSubdeps: true
minimumReleaseAge: 4320
trustPolicy: no-downgrade
patchedDependencies:
  openapi-typescript: patches/openapi-typescript.patch
overrides:
  'vite@>=7.0.0 <=7.3.1': '>=7.3.2'
  'vite@>=7.1.0 <=7.3.1': '>=7.3.2'
allowBuilds:
  esbuild: true
