# please use port numbers in the 30000 range so that it doesn't conflict with the main dev environment
services:
  kafka:
    extends:
      file: ../docker-compose.base.yaml
      service: kafka

  clickhouse:
    extends:
      file: ../docker-compose.base.yaml
      service: clickhouse

  redis:
    extends:
      file: ../docker-compose.base.yaml
      service: redis

  postgres:
    extends:
      file: ../docker-compose.base.yaml
      service: postgres

configs:
  svix_sql:
    content: |
      CREATE USER svix WITH PASSWORD 'svix';
      CREATE DATABASE svix;
      GRANT ALL PRIVILEGES ON DATABASE svix TO svix;
      ALTER DATABASE svix OWNER TO svix;
