package productcatalog

import "github.com/openmeterio/openmeter/internal/productcatalog"

type CreateFeatureInputs = productcatalog.CreateFeatureInputs
type FeatureRepoCreateFeatureInputs = productcatalog.FeatureRepoCreateFeatureInputs
type Feature = productcatalog.Feature
type FeatureConnector = productcatalog.FeatureConnector
type FeatureRepo = productcatalog.FeatureRepo
type FeatureInvalidFiltersError = productcatalog.FeatureInvalidFiltersError
type FeatureInvalidMeterAggregationError = productcatalog.FeatureInvalidMeterAggregationError
type FeatureNotFoundError = productcatalog.FeatureNotFoundError
type FeatureOrderBy = productcatalog.FeatureOrderBy
type FeatureWithNameAlreadyExistsError = productcatalog.FeatureWithNameAlreadyExistsError
type ListFeaturesParams = productcatalog.ListFeaturesParams
