name: Shared Steps
runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        # Runs quick, run rm in background
        tool-cache: true

        # These run slower as use apt to uninstall packages
        # Turned on by default, so we disable them
        android: false
        dotnet: false
        haskell: false
        large-packages: false
        docker-images: false
        swap-storage: false
