config:
  events:
    enabled: true
  notification:
    enabled: true
  entitlements:
    enabled: true
  meters:
    # Sample meter to count API requests
    - slug: api_requests_total # Unique identifier for the meter
      description: API Requests
      eventType: request # Filter events by type
      aggregation: COUNT # Aggregation method: COUNT, SUM, etc.
      groupBy:
        method: $.method # HTTP Method: GET, POST, etc.
        route: $.route # Route: /products/:product_id

    # Sample meter to count LLM Token Usage
    - slug: tokens_total
      description: AI Token Usage
      eventType: prompt # Filter events by type
      aggregation: SUM
      valueProperty: $.tokens # JSONPath to parse usage value
      groupBy:
        model: $.model # AI model used: gpt4-turbo, etc.
        type: $.type # Prompt type: input, output, system
