apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  annotations:
    openmeter.io/subject: customer-1
    data.openmeter.io/customer_group: platinum
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  annotations:
    openmeter.io/subject: customer-1
    data.openmeter.io/customer_group: platinum
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  annotations:
    openmeter.io/subject: customer-2
    data.openmeter.io/customer_group: gold
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  annotations:
    openmeter.io/subject: customer-3
    data.openmeter.io/customer_group: gold
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  annotations:
    openmeter.io/subject: customer-3
    data.openmeter.io/customer_group: gold
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-6
  annotations:
    openmeter.io/subject: customer-3
    data.openmeter.io/customer_group: gold
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo The app is running! && sleep 3600"]
