{{- if .Values.postgresql.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "openmeter.componentName" (list . "migrate-postgres") }}
  labels:
    {{- include "openmeter.componentLabels" (list . "migrate-postgres") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "openmeter.componentLabels" (list . "migrate-postgres") | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "openmeter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "openmeter.init.postgres" (list .) | nindent 8 }}
      containers:
        - name: migrate-postgres
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint.sh", "openmeter-jobs"]
          args: ["--config", "/etc/openmeter/config.yaml", "migrate", "postgres"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/openmeter
            {{- if ne (len .Values.caRootCertificates) 0 }}
            - name: ca-certificates
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openmeter.fullname" . }}
        {{- if ne (len .Values.caRootCertificates) 0 }}
        - name: ca-certificates
          configMap:
            name: ca-certificates
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- if .Values.clickhouse.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "openmeter.componentName" (list . "migrate-clickhouse") }}
  labels:
    {{- include "openmeter.componentLabels" (list . "migrate-clickhouse") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "openmeter.componentLabels" (list . "migrate-clickhouse") | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "openmeter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "openmeter.init.clickhouse" (list .) | nindent 8 }}
      containers:
        - name: migrate-clickhouse
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint.sh", "openmeter-jobs"]
          args: ["--config", "/etc/openmeter/config.yaml", "migrate", "clickhouse"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/openmeter
            {{- if ne (len .Values.caRootCertificates) 0 }}
            - name: ca-certificates
              mountPath: /usr/local/share/ca-certificates
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openmeter.fullname" . }}
        {{- if ne (len .Values.caRootCertificates) 0 }}
        - name: ca-certificates
          configMap:
            name: ca-certificates
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
