package httpdriver

import "github.com/openmeterio/openmeter/internal/entitlement/httpdriver"

// requests
type CreateEntitlementHandlerRequest = httpdriver.CreateEntitlementHandlerRequest
type CreateGrantHandlerRequest = httpdriver.CreateGrantHandlerRequest
type GetEntitlementBalanceHistoryHandlerRequest = httpdriver.GetEntitlementBalanceHistoryHandlerRequest
type GetEntitlementValueHandlerRequest = httpdriver.GetEntitlementValueHandlerRequest
type GetEntitlementsOfSubjectHandlerRequest = httpdriver.GetEntitlementsOfSubjectHandlerRequest
type ListEntitlementGrantHandlerRequest = httpdriver.ListEntitlementGrantHandlerRequest
type ResetEntitlementUsageHandlerRequest = httpdriver.ResetEntitlementUsageHandlerRequest
type ListEntitlementsHandlerRequest = httpdriver.ListEntitlementsHandlerRequest

// responses
type CreateEntitlementHandlerResponse = httpdriver.CreateEntitlementHandlerResponse
type CreateGrantHandlerResponse = httpdriver.CreateGrantHandlerResponse
type GetEntitlementBalanceHistoryHandlerResponse = httpdriver.GetEntitlementBalanceHistoryHandlerResponse
type GetEntitlementValueHandlerResponse = httpdriver.GetEntitlementValueHandlerResponse
type GetEntitlementsOfSubjectHandlerResponse = httpdriver.GetEntitlementsOfSubjectHandlerResponse
type ListEntitlementGrantHandlerResponse = httpdriver.ListEntitlementGrantHandlerResponse
type ResetEntitlementUsageHandlerResponse = httpdriver.ResetEntitlementUsageHandlerResponse
type ListEntitlementsHandlerResponse = httpdriver.ListEntitlementsHandlerResponse

// params
type CreateEntitlementHandlerParams = httpdriver.CreateEntitlementHandlerParams
type CreateGrantHandlerParams = httpdriver.CreateGrantHandlerParams
type GetEntitlementBalanceHistoryHandlerParams = httpdriver.GetEntitlementBalanceHistoryHandlerParams
type GetEntitlementValueHandlerParams = httpdriver.GetEntitlementValueHandlerParams
type GetEntitlementsOfSubjectHandlerParams = httpdriver.GetEntitlementsOfSubjectHandlerParams
type ListEntitlementGrantsHandlerParams = httpdriver.ListEntitlementGrantsHandlerParams
type ResetEntitlementUsageHandlerParams = httpdriver.ResetEntitlementUsageHandlerParams
type ListEntitlementsHandlerParams = httpdriver.ListEntitlementsHandlerParams
