// Code generated by ent, DO NOT EDIT.

package charge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openmeterio/openmeter/openmeter/billing/charges/meta"
	"github.com/openmeterio/openmeter/openmeter/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Charge {
	return predicate.Charge(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Charge {
	return predicate.Charge(sql.FieldContainsFold(FieldID, id))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldNamespace, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldCreatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldDeletedAt, v))
}

// UniqueReferenceID applies equality check predicate on the "unique_reference_id" field. It's identical to UniqueReferenceIDEQ.
func UniqueReferenceID(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldUniqueReferenceID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldEQ(FieldType, vc))
}

// ChargeFlatFeeID applies equality check predicate on the "charge_flat_fee_id" field. It's identical to ChargeFlatFeeIDEQ.
func ChargeFlatFeeID(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldChargeFlatFeeID, v))
}

// ChargeCreditPurchaseID applies equality check predicate on the "charge_credit_purchase_id" field. It's identical to ChargeCreditPurchaseIDEQ.
func ChargeCreditPurchaseID(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldChargeCreditPurchaseID, v))
}

// ChargeUsageBasedID applies equality check predicate on the "charge_usage_based_id" field. It's identical to ChargeUsageBasedIDEQ.
func ChargeUsageBasedID(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldChargeUsageBasedID, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContainsFold(FieldNamespace, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldCreatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Charge {
	return predicate.Charge(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Charge {
	return predicate.Charge(sql.FieldNotNull(FieldDeletedAt))
}

// UniqueReferenceIDEQ applies the EQ predicate on the "unique_reference_id" field.
func UniqueReferenceIDEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDNEQ applies the NEQ predicate on the "unique_reference_id" field.
func UniqueReferenceIDNEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDIn applies the In predicate on the "unique_reference_id" field.
func UniqueReferenceIDIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldUniqueReferenceID, vs...))
}

// UniqueReferenceIDNotIn applies the NotIn predicate on the "unique_reference_id" field.
func UniqueReferenceIDNotIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldUniqueReferenceID, vs...))
}

// UniqueReferenceIDGT applies the GT predicate on the "unique_reference_id" field.
func UniqueReferenceIDGT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDGTE applies the GTE predicate on the "unique_reference_id" field.
func UniqueReferenceIDGTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDLT applies the LT predicate on the "unique_reference_id" field.
func UniqueReferenceIDLT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDLTE applies the LTE predicate on the "unique_reference_id" field.
func UniqueReferenceIDLTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDContains applies the Contains predicate on the "unique_reference_id" field.
func UniqueReferenceIDContains(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContains(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDHasPrefix applies the HasPrefix predicate on the "unique_reference_id" field.
func UniqueReferenceIDHasPrefix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasPrefix(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDHasSuffix applies the HasSuffix predicate on the "unique_reference_id" field.
func UniqueReferenceIDHasSuffix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasSuffix(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDIsNil applies the IsNil predicate on the "unique_reference_id" field.
func UniqueReferenceIDIsNil() predicate.Charge {
	return predicate.Charge(sql.FieldIsNull(FieldUniqueReferenceID))
}

// UniqueReferenceIDNotNil applies the NotNil predicate on the "unique_reference_id" field.
func UniqueReferenceIDNotNil() predicate.Charge {
	return predicate.Charge(sql.FieldNotNull(FieldUniqueReferenceID))
}

// UniqueReferenceIDEqualFold applies the EqualFold predicate on the "unique_reference_id" field.
func UniqueReferenceIDEqualFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEqualFold(FieldUniqueReferenceID, v))
}

// UniqueReferenceIDContainsFold applies the ContainsFold predicate on the "unique_reference_id" field.
func UniqueReferenceIDContainsFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContainsFold(FieldUniqueReferenceID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...meta.ChargeType) predicate.Charge {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Charge(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...meta.ChargeType) predicate.Charge {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Charge(sql.FieldNotIn(FieldType, v...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldGT(FieldType, vc))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldGTE(FieldType, vc))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldLT(FieldType, vc))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldLTE(FieldType, vc))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldContains(FieldType, vc))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldHasPrefix(FieldType, vc))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldHasSuffix(FieldType, vc))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldEqualFold(FieldType, vc))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v meta.ChargeType) predicate.Charge {
	vc := string(v)
	return predicate.Charge(sql.FieldContainsFold(FieldType, vc))
}

// ChargeFlatFeeIDEQ applies the EQ predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDNEQ applies the NEQ predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDNEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDIn applies the In predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldChargeFlatFeeID, vs...))
}

// ChargeFlatFeeIDNotIn applies the NotIn predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDNotIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldChargeFlatFeeID, vs...))
}

// ChargeFlatFeeIDGT applies the GT predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDGT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDGTE applies the GTE predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDGTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDLT applies the LT predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDLT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDLTE applies the LTE predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDLTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDContains applies the Contains predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDContains(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContains(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDHasPrefix applies the HasPrefix predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDHasPrefix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasPrefix(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDHasSuffix applies the HasSuffix predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDHasSuffix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasSuffix(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDIsNil applies the IsNil predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDIsNil() predicate.Charge {
	return predicate.Charge(sql.FieldIsNull(FieldChargeFlatFeeID))
}

// ChargeFlatFeeIDNotNil applies the NotNil predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDNotNil() predicate.Charge {
	return predicate.Charge(sql.FieldNotNull(FieldChargeFlatFeeID))
}

// ChargeFlatFeeIDEqualFold applies the EqualFold predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDEqualFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEqualFold(FieldChargeFlatFeeID, v))
}

// ChargeFlatFeeIDContainsFold applies the ContainsFold predicate on the "charge_flat_fee_id" field.
func ChargeFlatFeeIDContainsFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContainsFold(FieldChargeFlatFeeID, v))
}

// ChargeCreditPurchaseIDEQ applies the EQ predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDNEQ applies the NEQ predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDNEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDIn applies the In predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldChargeCreditPurchaseID, vs...))
}

// ChargeCreditPurchaseIDNotIn applies the NotIn predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDNotIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldChargeCreditPurchaseID, vs...))
}

// ChargeCreditPurchaseIDGT applies the GT predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDGT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDGTE applies the GTE predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDGTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDLT applies the LT predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDLT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDLTE applies the LTE predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDLTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDContains applies the Contains predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDContains(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContains(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDHasPrefix applies the HasPrefix predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDHasPrefix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasPrefix(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDHasSuffix applies the HasSuffix predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDHasSuffix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasSuffix(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDIsNil applies the IsNil predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDIsNil() predicate.Charge {
	return predicate.Charge(sql.FieldIsNull(FieldChargeCreditPurchaseID))
}

// ChargeCreditPurchaseIDNotNil applies the NotNil predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDNotNil() predicate.Charge {
	return predicate.Charge(sql.FieldNotNull(FieldChargeCreditPurchaseID))
}

// ChargeCreditPurchaseIDEqualFold applies the EqualFold predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDEqualFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEqualFold(FieldChargeCreditPurchaseID, v))
}

// ChargeCreditPurchaseIDContainsFold applies the ContainsFold predicate on the "charge_credit_purchase_id" field.
func ChargeCreditPurchaseIDContainsFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContainsFold(FieldChargeCreditPurchaseID, v))
}

// ChargeUsageBasedIDEQ applies the EQ predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEQ(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDNEQ applies the NEQ predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDNEQ(v string) predicate.Charge {
	return predicate.Charge(sql.FieldNEQ(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDIn applies the In predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldIn(FieldChargeUsageBasedID, vs...))
}

// ChargeUsageBasedIDNotIn applies the NotIn predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDNotIn(vs ...string) predicate.Charge {
	return predicate.Charge(sql.FieldNotIn(FieldChargeUsageBasedID, vs...))
}

// ChargeUsageBasedIDGT applies the GT predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDGT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGT(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDGTE applies the GTE predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDGTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldGTE(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDLT applies the LT predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDLT(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLT(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDLTE applies the LTE predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDLTE(v string) predicate.Charge {
	return predicate.Charge(sql.FieldLTE(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDContains applies the Contains predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDContains(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContains(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDHasPrefix applies the HasPrefix predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDHasPrefix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasPrefix(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDHasSuffix applies the HasSuffix predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDHasSuffix(v string) predicate.Charge {
	return predicate.Charge(sql.FieldHasSuffix(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDIsNil applies the IsNil predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDIsNil() predicate.Charge {
	return predicate.Charge(sql.FieldIsNull(FieldChargeUsageBasedID))
}

// ChargeUsageBasedIDNotNil applies the NotNil predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDNotNil() predicate.Charge {
	return predicate.Charge(sql.FieldNotNull(FieldChargeUsageBasedID))
}

// ChargeUsageBasedIDEqualFold applies the EqualFold predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDEqualFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldEqualFold(FieldChargeUsageBasedID, v))
}

// ChargeUsageBasedIDContainsFold applies the ContainsFold predicate on the "charge_usage_based_id" field.
func ChargeUsageBasedIDContainsFold(v string) predicate.Charge {
	return predicate.Charge(sql.FieldContainsFold(FieldChargeUsageBasedID, v))
}

// HasFlatFee applies the HasEdge predicate on the "flat_fee" edge.
func HasFlatFee() predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, FlatFeeTable, FlatFeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlatFeeWith applies the HasEdge predicate on the "flat_fee" edge with a given conditions (other predicates).
func HasFlatFeeWith(preds ...predicate.ChargeFlatFee) predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := newFlatFeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreditPurchase applies the HasEdge predicate on the "credit_purchase" edge.
func HasCreditPurchase() predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, CreditPurchaseTable, CreditPurchaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreditPurchaseWith applies the HasEdge predicate on the "credit_purchase" edge with a given conditions (other predicates).
func HasCreditPurchaseWith(preds ...predicate.ChargeCreditPurchase) predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := newCreditPurchaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageBased applies the HasEdge predicate on the "usage_based" edge.
func HasUsageBased() predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UsageBasedTable, UsageBasedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageBasedWith applies the HasEdge predicate on the "usage_based" edge with a given conditions (other predicates).
func HasUsageBasedWith(preds ...predicate.ChargeUsageBased) predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := newUsageBasedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBillingInvoiceLines applies the HasEdge predicate on the "billing_invoice_lines" edge.
func HasBillingInvoiceLines() predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BillingInvoiceLinesTable, BillingInvoiceLinesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillingInvoiceLinesWith applies the HasEdge predicate on the "billing_invoice_lines" edge with a given conditions (other predicates).
func HasBillingInvoiceLinesWith(preds ...predicate.BillingInvoiceLine) predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := newBillingInvoiceLinesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBillingSplitLineGroups applies the HasEdge predicate on the "billing_split_line_groups" edge.
func HasBillingSplitLineGroups() predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BillingSplitLineGroupsTable, BillingSplitLineGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillingSplitLineGroupsWith applies the HasEdge predicate on the "billing_split_line_groups" edge with a given conditions (other predicates).
func HasBillingSplitLineGroupsWith(preds ...predicate.BillingInvoiceSplitLineGroup) predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := newBillingSplitLineGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreditRealizationLineages applies the HasEdge predicate on the "credit_realization_lineages" edge.
func HasCreditRealizationLineages() predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CreditRealizationLineagesTable, CreditRealizationLineagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreditRealizationLineagesWith applies the HasEdge predicate on the "credit_realization_lineages" edge with a given conditions (other predicates).
func HasCreditRealizationLineagesWith(preds ...predicate.CreditRealizationLineage) predicate.Charge {
	return predicate.Charge(func(s *sql.Selector) {
		step := newCreditRealizationLineagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Charge) predicate.Charge {
	return predicate.Charge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Charge) predicate.Charge {
	return predicate.Charge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Charge) predicate.Charge {
	return predicate.Charge(sql.NotPredicates(p))
}
