
[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openmeter"
authors = [
  { name = "" },
]
description = " OpenMeter Client Library for Python"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.9"

dependencies = [
    "isodate>=0.6.1",
    "corehttp[requests]>=1.0.0b6",
    "typing-extensions>=4.6.0",
]
dynamic = [
"version", "readme"
]

[tool.setuptools.dynamic]
version = {attr = "openmeter._version.VERSION"}
readme = {file = ["README.md", "CHANGELOG.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
exclude = [
    "tests*",
    "samples*",
    "doc*",
]

[tool.setuptools.package-data]
pytyped = ["py.typed"]
