// Code generated by @openmeter/typespec-go. DO NOT EDIT.

package components

import "encoding/json"

// Type of a charge.
//
// Values:
//
// - `flat_fee`: A fixed-amount charge.
// - `usage_based`: A usage-priced charge.
type BillingChargeType string

const (
	BillingChargeTypeFlatFee    BillingChargeType = "flat_fee"
	BillingChargeTypeUsageBased BillingChargeType = "usage_based"
	BillingChargeTypeUnknown    BillingChargeType = "UNKNOWN"
)

func (e BillingChargeType) ToPointer() *BillingChargeType {
	return &e
}

func (e *BillingChargeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*e = BillingChargeType(v)
	return nil
}
