// Code generated by @openmeter/typespec-go. DO NOT EDIT.

package components

import "github.com/openmeterio/openmeter/api/spec/packages/aip-client-go/internal/utils"

// TaxCode created response.
type CreateTaxCodeResponse struct {
}

func (c CreateTaxCodeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTaxCodeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}
