// Code generated by @openmeter/typespec-go. DO NOT EDIT.

package components

import "github.com/openmeterio/openmeter/api/spec/packages/aip-client-go/internal/utils"

// Determines which page of the collection to retrieve.
type CursorPaginationQueryPage struct {
	// The number of items to include per page.
	Size *int64 `json:"size,omitzero"`
	// Request the next page of data, starting with the item after this parameter.
	After *string `json:"after,omitzero"`
	// Request the previous page of data, starting with the item before this parameter.
	Before *string `json:"before,omitzero"`
}

func (c CursorPaginationQueryPage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CursorPaginationQueryPage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CursorPaginationQueryPage) GetSize() *int64 {
	if c == nil {
		return nil
	}
	return c.Size
}

func (c *CursorPaginationQueryPage) GetAfter() *string {
	if c == nil {
		return nil
	}
	return c.After
}

func (c *CursorPaginationQueryPage) GetBefore() *string {
	if c == nil {
		return nil
	}
	return c.Before
}
