name: Python SDK Beta Release

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-beta-sdk:
    name: Python SDK Beta Release
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
          use-policy-store: ${{ secrets.STEP_SECURITY_API_KEY != '' }}
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get short SHA
        id: get-short-sha
        run: |
          echo "id=${GITHUB_SHA:0:12}" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: python -m pip install poetry==2.4.1

      - name: Publish Python package
        run: make -C api/client/python publish-python-sdk
        env:
          PY_SDK_RELEASE_TAG: alpha
          COMMIT_SHORT_SHA: ${{ steps.get-short-sha.outputs.id }}
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
