name: JavaScript SDK

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/openapi.cloud.yaml
      - .github/workflows/sdk-node.yaml
env:
  DAGGER_VERSION: 0.15.2

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - name: Generate
        uses: dagger/dagger-for-github@31393402b06d9d3524e2bc67a14f63d1462821ab # v7.0.5
        with:
          verb: call
          args: generate javascript-sdk -o api/client/javascript
          cloud-token: ${{ secrets.DAGGER_CLOUD_NO_CACHE_TOKEN }}
          version: ${{ env.DAGGER_VERSION }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: openapi/javascript-sdk
          branch-suffix: short-commit-hash
          delete-branch: true
          commit-message: "chore(api): generate javascript client"
          title: "[bot] Re-generate JavaScript client"
          body: "This PR was automatically generated."
          labels: |
            area/api
            release-note/misc
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
