permissions:
  contents: read
  actions: read
  checks: read
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Security

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
          use-policy-store: ${{ secrets.STEP_SECURITY_API_KEY != '' }}
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: Kong/public-shared-actions/security-actions/secret-scan@43112b0f261fbe0ba7551cba05fba936a7532b58 # 1.1.1
        name: Running Secret Scan using Trufflehog
        with:
          fail_on_findings: "true"

  sca:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
    name: Repository Scan
    if: (github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
          use-policy-store: ${{ secrets.STEP_SECURITY_API_KEY != '' }}
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Scan Repository
        id: sca_repo
        uses: Kong/public-shared-actions/security-actions/sca@43112b0f261fbe0ba7551cba05fba936a7532b58 # 6.0.0
        with:
          asset_prefix: openmeter-cloud
          dir: "."
          config: .syft.yaml
          fail_build: "true"

  scan-gh-workflows:
    name: Scan GitHub Workflows
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
          use-policy-store: ${{ secrets.STEP_SECURITY_API_KEY != '' }}
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Scan GitHub Workflows
        id: scan_gh_workflows
        uses: Kong/public-shared-actions/security-actions/scan-gh-workflows@43112b0f261fbe0ba7551cba05fba936a7532b58 # 5.0.2
        with:
          fail_on_findings: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
