// Code generated by @openmeter/typespec-typescript. DO NOT EDIT.

import { z } from 'zod'
import * as schemas from '../schemas.js'
import type { AcceptDateStrings } from '../../lib/wire.js'
import type {
  App,
  AppCatalogItem,
  AppCatalogItemPagePaginatedResponse,
  AppPagePaginatedResponse,
  BillingInstallAppResponse,
  InstallAppRequest as InstallAppRequestBody,
  ListAppsParamsFilter,
  SortQueryInput,
  UpdateAppRequest as UpdateAppRequestBody,
} from '../types.js'

export interface ListAppsQuery {
  /** Determines which page of the collection to retrieve. */
  page?: { size?: number; number?: number }
  /**
   * Sort apps returned in the response. Supported sort attributes are:
   *
   * - `id`
   * - `created_at` (default)
   *
   * The `asc` suffix is optional as the default sort order is ascending. The `desc`
   * suffix is used to specify a descending order.
   */
  sort?: SortQueryInput
  /**
   * Filter apps returned in the response.
   *
   * To filter apps by name add the following query param: filter[name]=my-app
   */
  filter?: ListAppsParamsFilter
}

export type ListAppsRequest = AcceptDateStrings<ListAppsQuery>
export type ListAppsResponse = AppPagePaginatedResponse

export type GetAppRequest = {
  appId: string
}
export type GetAppResponse = App

export type UninstallAppRequest = {
  appId: string
}
export type UninstallAppResponse = void

export type UpdateAppRequest = AcceptDateStrings<{
  appId: string
  body: UpdateAppRequestBody
}>
export type UpdateAppResponse = App

export interface ListAppCatalogQuery {
  /** Determines which page of the collection to retrieve. */
  page?: { size?: number; number?: number }
}

export type ListAppCatalogRequest = AcceptDateStrings<ListAppCatalogQuery>
export type ListAppCatalogResponse = AppCatalogItemPagePaginatedResponse

export type GetAppCatalogItemRequest = {
  appType: string
}
export type GetAppCatalogItemResponse = AppCatalogItem

export type InstallAppRequest = AcceptDateStrings<InstallAppRequestBody>
export type InstallAppResponse = BillingInstallAppResponse
