package invalidparameterrules

const (
	Required         = "required"
	Unique           = "unique"
	DependentFields  = "dependent_fields"
	Enum             = "enum"
	MinLength        = "min_length"
	MaxLength        = "max_length"
	MinItems         = "min_items"
	MaxItems         = "max_items"
	Min              = "min"
	Max              = "max"
	MinDigits        = "min_digits"
	MinLowercase     = "min_lowercase"
	MinUppercase     = "min_uppercase"
	MinSymbols       = "min_symbols"
	MinTime          = "min_time"
	MaxTime          = "max_time"
	IsArray          = "is_array"
	IsBoolean        = "is_boolean"
	IsDateTime       = "is_date_time"
	IsInteger        = "is_integer"
	IsNull           = "is_null"
	IsNumber         = "is_number"
	IsObject         = "is_object"
	IsString         = "is_string"
	IsUUID           = "is_uuid"
	UnknownProperty  = "unknown_property"
	MissingReference = "missing_reference"
)
